DROP TABLE IF EXISTS `austria_diplomatic_entity`;
CREATE TABLE `austria_diplomatic_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `austria_diplomatic_entity` WRITE;
INSERT INTO `austria_diplomatic_entity` (description, region) VALUES
('Vatican City','1'),
('South Africa','2'),
('Albania','3'),
('Germany','4'),
('United States','5'),
('Saudi Arabia','6'),
('Egypt','7'),
('Argentina','8'),
('Australia','9'),
('Belgium','11'),
('Brazil','12'),
('Bulgaria','13'),
('Canada','14'),
('Chile','15'),
('Colombia','16'),
('South Korea','17'),
('Cuba','18'),
('Denmark','19'),
('Luxembourg (formerly  El Salvador?)','21'),
('Spain','22'),
('Finland','23'),
('France','24'),
('United Kingdom','25'),
('Greece','26'),
('Hungary','27'),
('India','28'),
('Indonesia','29'),
('Iraq','31'),
('Iran','32'),
('Israel','33'),
('Italy','34'),
('Japan','35'),
('Lebanon','36'),
('Mexico','37'),
('Norway','38'),
('Sovereign Military Order of Malta','39'),
('Pakistan','41'),
('Panama','42'),
('Netherlands','43'),
('Peru','44'),
('Poland','45'),
('Portugal','46'),
('Romania','47'),
('Sweden','48'),
('Switzerland','49'),
('Czech Republic','51'),
('Thailand','52'),
('Turkey','53'),
('Russia','54'),
('Ukraine','55'),
('Venezuela','56'),
('Serbia (formerly  Serbia and Montenegro?)','57'),
('Ecuador','58'),
('Tunisia','59'),
('Morocco','61'),
('Democratic Republic of the Congo (formerly  Zaire)','62'),
('Algeria (formerly  Gabon?)','63'),
('China','64'),
('Syria','65'),
('Libya','66'),
('Costa Rica','67'),
('Comprehensive Nuclear-Test-Ban Treaty Organization (formerly  East Germany)','68'),
('Guatemala','69'),
('Ivory Coast','71'),
('Malaysia','72'),
('New Zealand','73'),
('Philippines','74'),
('Nigeria','75'),
('Oman','76'),
('Ireland','77'),
('North Korea','78'),
('Qatar','79'),
('International Atomic Energy Agency','81'),
('United Nations United Nations Industrial Development Organization','82'),
('United Nations United Nations High Commissioner for Refugees','83'),
('UNCB','84'),
('United Nations United Nations Relief and Works Agency for Palestine Refugees in the Near East','85'),
('Nicaragua','86'),
('International Atomic Energy Agency','87'),
('Kuwait','88'),
('United Nations United Nations Industrial Development Organization','89'),
('Organization of the Petroleum Exporting Countries','91'),
('International Organization for Migration','92'),
('United Arab Emirates','93'),
('Senegal','94'),
('Jordan','95'),
('OPEC Fund for International Development','96'),
('Arab League','97'),
('European Union','98'),
('Organization for Security and Co-operation in Europe','247'),
('Slovakia','515'),
('Organization for Security and Co-operation in Europe','532'),
('Vietnam','551'),
('Kenya','622'),
('Azerbaijan/  Namibia/  Zimbabwe?','623'),
('Cape Verde','624'),
('Ethiopia','677'),
('Armenia','678'),
('Slovenia','712'),
('North Macedonia','718'),
('Montenegro','723'),
('Estonia','726'),
('Latvia','728'),
('Malta','846'),
('Tajikistan','853'),
('Kazakhstan','858'),
('Georgia','859'),
('China','872'),
('Angola','891'),
('Cyprus','982'),
('Bolivia','995');
UNLOCK TABLES;

ALTER TABLE austria_diplomatic_entity ADD INDEX austria_diplomatic_index (description, region);