DROP TABLE IF EXISTS `italian_diplomatic_entity`;
CREATE TABLE `italian_diplomatic_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `italian_diplomatic_entity` WRITE;
INSERT INTO `italian_diplomatic_entity` (description, region) VALUES
('Albania','AA'),
('Austria','AC'),
('Belgium','AE'),
('Bulgaria','AG'),
('Czech Republic','AK'),
('Cyprus','AM'),
('Denmark','AN'),
('Finland','AP'),
('France','AQ'),
('Germany','AU'),
('West Germany','AV'),
('East Germany','BA'),
('United Kingdom','BC'),
('Slovenia','BF'),
('Greece','BG'),
('Ireland','BM'),
('Italy (Holy See)','BN'),
('Serbia','BP'),
('Croatia','BQ'),
('Luxembourg','BR'),
('Malta','BS'),
('Monaco','BT'),
('Norway','BV'),
('Netherlands','BX'),
('Poland','CA'),
('Portugal','CC'),
('Romania','CE'),
('San Marino','CG'),
('Spain','CH'),
('Switzerland','CM'),
('Sweden','CN'),
('Switzerland','CQ'),
('Turkey','CR'),
('Hungary','CX'),
('Russia (formerly  Soviet Union)','DA'),
('Ukraine','DC'),
('Uzbekistan','DD'),
('Vatican City (Apostolic Nunciature)','DE'),
('Slovenia','DF'),
('North Macedonia','DG'),
('Bosnia and Herzegovina','DH'),
('Slovakia','DL'),
('Armenia','DM'),
('Georgia','DN'),
('Kazakhstan','DP'),
('Latvia','DQ'),
('Belarus','DR'),
('Lithuania','DS'),
('Moldova','DT'),
('Iceland','DV'),
('Azerbaijan','DZ'),
('Burkina Faso','EA'),
('Dominica','EB'),
('Uganda','EC'),
('Burundi','ED'),
('Rwanda','EF'),
('Zimbabwe','EG'),
('Qatar','EH'),
('Chad','EL'),
('Mauritania','EM'),
('Eritrea','EN'),
('Mali','EP'),
('Belize','ER'),
('Equatorial Guinea (c/o FAO)','ES'),
('Kosovo','ET'),
('Afghanistan','GA'),
('Saudi Arabia','GB'),
('Bangladesh','GC'),
('Myanmar','GD'),
('Taiwan','GE'),
('China','GF'),
('Philippines','GQ'),
('North Korea','GS'),
('South Korea','GM'),
('United Arab Emirates','GP'),
('Japan','GS'),
('Jordan','GZ'),
('India','HA'),
('Indonesia','HC'),
('Iran','HE'),
('Iraq','HF'),
('Israel','HL'),
('Iraq','HP'),
('Kuwait','HQ'),
('Lebanon','HR'),
('Malaysia','HS'),
('Oman','HT'),
('Pakistan','HV'),
('Syria','HX'),
('Sri Lanka','LA'),
('Thailand','LB'),
('Vietnam','LE'),
('Yemen','LF'),
('Montenegro','LH'),
('Timor-Leste','LM'),
('Algeria','NA'),
('Angola','NC'),
('Cameroon','ND'),
('Cape Verde','NF'),
('Central African Republic','NG'),
('Republic of the Congo','NH'),
('Ivory Coast','NL'),
('Egypt','NM'),
('Ethiopia','NR'),
('Gabon','NT'),
('Ghana','NX'),
('Guinea','PA'),
('Kenya','PB'),
('Lesotho','PC'),
('Liberia','PD'),
('Libya','PE'),
('Madagascar','PL'),
('Morocco','PN'),
('Nigeria','PQ'),
('Senegal','PS'),
('Sierra Leone','PT'),
('Mozambique','PV'),
('Somalia','PX'),
('South Africa','QA'),
('Sudan','QC'),
('Tanzania','QE'),
('Tunisia','QG'),
('Democratic Republic of the Congo','QL'),
('Zambia','QN'),
('Niger','QP'),
('Canada','SA'),
('Mexico','SD'),
('United States','SF'),
('United States','SH'),
('United States','SL'),
('United States','SN'),
('United States','SQ'),
('Costa Rica','TA'),
('Cuba','TC'),
('Dominican Republic','TE'),
('Ecuador','TF'),
('Jamaica','TG'),
('Guatemala','TH'),
('Haiti','TL'),
('Honduras','TM'),
('Nicaragua','TP'),
('Panama','TQ'),
('El Salvador','TS'),
('Argentina','UA'),
('Bolivia','UE'),
('Brazil','UF'),
('Chile','UH'),
('Colombia','UL'),
('Paraguay','UN'),
('Peru','UP'),
('Uruguay','US'),
('Venezuela','UT'),
('Argentina','VA'),
('Brazil','VF'),
('Colombia','VL'),
('Uruguay','VS'),
('S.M.O.M and  Palestine','XA'),
('FAO,  United Nations, International organizations, and  European Union','XC'),
('FAO,  United Nations, International organizations, and  European Union','XD'),
('FAO,  United Nations, International organizations, and  European Union','XE'),
('FAO,  United Nations, International organizations, and  European Union','XF'),
('FAO,  United Nations, International organizations, and  European Union','XH'),
('Vatican City','XG'),
('Australia','ZA'),
('New Zealand','ZC'),
('Philippines','GQ');
UNLOCK TABLES;

ALTER TABLE italian_diplomatic_entity ADD INDEX italian_diplomatic_index (description, region);