DROP TABLE IF EXISTS `lithuania_diplomatic_entity`;
CREATE TABLE `lithuania_diplomatic_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `lithuania_diplomatic_entity` WRITE;
INSERT INTO `lithuania_diplomatic_entity` VALUES
('Sweden','01'),
('Germany','02'),
('France','03'),
('Latvia','04'),
('Denmark','05'),
('Canada','06'),
('United Kingdom','07'),
('Italy','08'),
('Norway','09'),
('Finland','10'),
('Holy See','11'),
('Turkey','12'),
('Czech Republic','13'),
('United States','14'),
('China','15'),
('Poland','16'),
('Poland','17'),
('Estonia','18'),
('Russia','19'),
('Russia','20'),
('Romania','21'),
('Ukraine','22'),
('Belarus','23'),
('Kazakhstan','24'),
('Georgia','25'),
('Japan','26'),
('Austria','27'),
('Belgium','28'),
('Netherlands','29'),
('Hungary','30'),
('Spain','31'),
('Sovereign Military Order of Malta','32'),
('Democratic Republic of Congo','33'),
('Ireland','34'),
('Portugal','35'),
('Moldova','36'),
('Azerbaijan','37'),
('Bulgaria','38'),
('Armenia','39'),
('Croatia','40'),
('Israel','41'),
('Nordic Council of Ministers','80'),
('International Bank for Reconstruction and Development','81'),
('European Bank for Reconstruction and Development','82'),
('World Health Organization','83'),
('United Nations United Nations Development Program','84'),
('International Organization for Migration','85'),
('European Union European Commission','86'),
('United Nations','87'),
('European Institute for Gender Equality','88'),
('NATO Energy Security Centre of Excellence','89');
UNLOCK TABLES;

ALTER TABLE lithuania_diplomatic_entity ADD INDEX lithuania_diplomatic_index (description, region);