DROP TABLE IF EXISTS `malaysia_diplomatic_entity`;
CREATE TABLE `malaysia_diplomatic_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `malaysia_diplomatic_entity` WRITE;
INSERT INTO `malaysia_diplomatic_entity` (description, region) VALUES
('Sri Lanka','10'),
('Thailand','11'),
('Switzerland','12'),
('Libya','14'),
('Australia','15'),
('United States','16'),
('Pakistan','17'),
('Germany','18'),
('Bangladesh','19'),
('Syria','21'),
('Canada','22'),
('Netherlands','23'),
('Russia','24'),
('Belgium','25'),
('Philippines','26'),
('Romania','27'),
('Indonesia','29'),
('Poland','30'),
('Eswatini','31'),
('Egypt','31'),
('Sweden','32'),
('Cambodia','34'),
('New Zealand','35'),
('South Korea','36'),
('Austria','37'),
('United Kingdom','38'),
('Singapore','39'),
('India','40'),
('Myanmar','41'),
('Vietnam','42'),
('Denmark','43'),
('Iraq','44'),
('Seychelles','45'),
('Japan','46'),
('France','47'),
('Saudi Arabia','48'),
('China','49'),
('Czech Republic','50'),
('Turkey','51'),
('Slovakia','52'),
('Finland','53'),
('Kuwait','54'),
('Brazil','55'),
('Timor-Leste','56'),
('Iran','57'),
('Brunei','58'),
('Oman','59'),
('Norway','60'),
('Palestine','61'),
('Argentina','62'),
('Ukraine','63'),
('Spain','64'),
('Fiji','65'),
('Morocco','66'),
('Mauritius','67'),
('Chile','68'),
('Sudan','69'),
('Nigeria','70'),
('Mexico','71'),
('Laos','72'),
('Venezuela','73'),
('Zimbabwe','74'),
('Hungary','75'),
('Peru','76'),
('Algeria','77'),
('Albania','78'),
('South Africa','79'),
('Bosnia and Herzegovina','80'),
('Ecuador','81'),
('Uruguay','82'),
('Ireland','83'),
('Colombia','84'),
('United Arab Emirates','85'),
('Croatia','86'),
('Afghanistan','87'),
('Namibia','88'),
('Uzbekistan','89'),
('Luxembourg','90'),
('Kenya','91'),
('Guinea','92'),
('Kazakhstan','93'),
('Ghana','94'),
('Kyrgyzstan','95'),
('Jordan','96'),
('Cuba','97'),
('Senegal','98'),
('Yemen','99'),
('European Union','100'),
('Nepal','101'),
('Papua New Guinea','102'),
('Lebanon','103'),
('Qatar','104'),
('Maldives','105'),
('Azerbaijan','107'),
('Zambia','109'),
('Vatican City','110'),
('Somalia','111'),
('Georgia','114'),
('Gambia','115'),
('Tajikistan','117');
UNLOCK TABLES;

ALTER TABLE malaysia_diplomatic_entity ADD INDEX malaysia_diplomatic_index (description, region);