DROP TABLE IF EXISTS `portugal_diplomatic_entity`;
CREATE TABLE `portugal_diplomatic_entity`
(
    `id`          bigint NOT NULL AUTO_INCREMENT,
    `description` varchar(255) DEFAULT NULL,
    `region`      varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK
TABLES `portugal_diplomatic_entity` WRITE;
INSERT INTO `portugal_diplomatic_entity` (description, region)
VALUES ('Afganistán', '001'),
       ('Sudáfrica', '002'),
       ('Albania', '003'),
       ('Alemania', '005'),
       ('Andorra', '006'),
       ('Angola', '007'),
       ('Antigua', '008'),
       ('Arabia Saudí', '009'),
       ('Argelia', '010'),
       ('Argentina', '011'),
       ('Australia', '012'),
       ('Austria', '013'),
       ('Bahamas', '014'),
       ('Bahrein', '015'),
       ('Bangladesh', '016'),
       ('Barbados', '017'),
       ('Bélgica', '018'),
       ('Belize', '019'),
       ('Bolivia', '022'),
       ('Brasil', '024'),
       ('Bulgaria', '025'),
       ('Cabo Verde', '029'),
       ('Camerún', '030'),
       ('Canadá', '031'),
       ('República Checa', '034'),
       ('China', '036'),
       ('Colombia', '038'),
       ('Costa Rica', '044'),
       ('El Salvador', '051'),
       ('Emiratos Árabes Unidos', '052'),
       ('Ecuador', '053'),
       ('España', '054'),
       ('Estados Unidos', '055'),
       ('Eslovaquia', '056'),
       ('Eslovenia', '057'),
       ('Filipinas', '058'),
       ('Finlandia', '059'),
       ('Francia', '060'),
       ('Gabon', '061'),
       ('Grecia', '065'),
       ('Guatemala', '066'),
       ('Guinea Ecuatorial', '070  '),
       ('Honduras', '072'),
       ('Hungría', '073'),
       ('Irlanda', '078'),
       ('Italia', '081'),
       ('Liechstenstein', '094'),
       ('Luxemburgo', '095'),
       ('Madagascar', '096'),
       ('SMOM', '101'),
       ('Malta', '102'),
       ('Marruecos', '103'),
       ('Mexico', '106'),
       ('Mónaco', '108'),
       ('Noruega', '115'),
       ('Omán', '117'),
       ('Panamá', '119'),
       ('Polonia', '124'),
       ('Qatar', '125'),
       ('Kenia', '126'),
       ('Reino Unido', '127'),
       ('Rumanía', '128'),
       ('Islas Salomón', '130'),
       ('San Marino', '132'),
       ('Vaticano', '134'),
       ('Senegal', '137'),
       ('Sierra Leona', '139'),
       ('Singapur', '140'),
       ('Siria', '141'),
       ('Sudán', '145'),
       ('Suecia', '146'),
       ('Suiza', '147'),
       ('Suriname', '148'),
       ('Tailandia', '149'),
       ('Tanzania', '150'),
       ('Taiwán', '151'),
       ('Togo', '152'),
       ('Tonga', '153'),
       ('Túnez', '155'),
       ('Turquía', '156'),
       ('Rusia', '158'),
       ('Venezuela', '161'),
       ('Palestina', '194'),
       ('Unión Europea', '200'),
       ('Consul de Europa', '203');
UNLOCK
TABLES;

ALTER TABLE portugal_diplomatic_entity
    ADD INDEX portugal_diplomatic_index (description, region);