DROP TABLE IF EXISTS `sweden_dip_entity`;
CREATE TABLE `sweden_dip_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `sweden_dip_entity` WRITE;
INSERT INTO `sweden_dip_entity` VALUES
(1,'South Africa','AA'),
(2,'Albania','AB'),
(3,'Algeria','AC'),
(4,'Germany','AD'),
(5,'Armenia','AE'),
(6,'United States','AF'),
(7,'Angola','AG'),
(8,'Saudi Arabia','AH'),
(9,'Argentina','AJ'),
(10,'Australia','AK'),
(11,'Austria','AL'),
(12,'Bangladesh','AM'),
(13,'Belgium','AN'),
(14,'Bolivia','AP'),
(15,'Botswana','AR'),
(16,'Brazil','AS'),
(17,'Bulgaria','AT'),
(18,'Canada','AU'),
(19,'Chile','AW'),
(20,'China','AX'),
(21,'Colombia','AY'),
(22,'South Korea','AZ'),
(23,'North Korea','BA'),
(24,'Cuba','BC'),
(25,'Denmark','BD'),
(26,'Dominican Republic','BE'),
(27,'Egypt','BF'),
(28,'Ecuador','BG'),
(29,'Spain','BH'),
(30,'Ethiopia','BJ'),
(31,'Finland','BK'),
(32,'France','BL'),
(33,'United Kingdom','BM'),
(34,'Greece','BN'),
(35,'Guatemala','BP'),
(36,'Hungary','BS'),
(37,'India','BT'),
(38,'Indonesia','BU'),
(39,'Iraq','BW'),
(40,'Iran','BX'),
(41,'Ireland','BY'),
(42,'Iceland','BZ'),
(43,'Israel','CA'),
(44,'Italy','CB'),
(45,'Japan','CC'),
(46,'Kenya','CD'),
(47,'Laos','CE'),
(48,'Lebanon','CF'),
(49,'Libya','CG'),
(50,'Malaysia','CH'),
(51,'Morocco','CJ'),
(52,'Mexico','CK'),
(53,'Mozambique','CL'),
(54,'Nicaragua','CM'),
(55,'Nigeria','CN'),
(56,'Norway','CP'),
(57,'Pakistan','CS'),
(58,'Panama','CT'),
(59,'Netherlands','CU'),
(60,'Peru','CW'),
(61,'Philippines','CX'),
(62,'Poland','CY'),
(63,'Portugal','CZ'),
(64,'Romania','DA'),
(65,'Senegal','DB'),
(66,'Somalia','DC'),
(67,'Sri Lanka','DD'),
(68,'Switzerland','DE'),
(69,'Tanzania','DF'),
(70,'Czech Republic','DG'),
(71,'Thailand','DH'),
(72,'Tunisia','DJ'),
(73,'Turkey','DK'),
(74,'Russia','DL'),
(75,'Uruguay','DM'),
(76,'Venezuela','DN'),
(77,'Vietnam','DP'),
(78,'Serbia','DR'),
(79,'Zambia','DS'),
(80,'Zimbabwe','DT'),
(81,'UNHCR','DU'),
(82,'World Maritime University','DW'),
(83,'Nordic Council','DX'),
(84,'Namibia','DY'),
(85,'Sudan','DZ'),
(86,'ESA','EA'),
(87,'European Union','EB'),
(88,'Burundi','EC'),
(89,'Estonia','ED'),
(90,'Latvia','EE'),
(91,'Lithuania','EF'),
(92,'Croatia','EG'),
(93,'Slovenia','EH'),
(94,'Slovakia','EJ'),
(95,'Bosnia and Herzegovina','EK'),
(96,'Eritrea','EL'),
(97,'Ukraine','EM'),
(98,'Cyprus','EN'),
(99,'Macedonia','EP'),
(100,'Kuwait','ER'),
(101,'Honduras','ES'),
(102,'Rwanda','ET'),
(103,'IDEA','EU'),
(104,'Cape Verde','EX'),
(105,'CBSS','EY'),
(106,'Belarus','FA'),
(107,'Congo','FB'),
(108,'El Salvador','FC'),
(109,'Syria','FD'),
(110,'GIWA','FE'),
(111,'Vatican City','FF'),
(112,'GWP','FH'),
(113,'United Arab Emirates','FJ'),
(114,'Moldova','FK'),
(115,'Georgia','FL'),
(116,'Azerbaijan','FM'),
(117,'New Zealand','FN');
UNLOCK TABLES;