version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"

    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: regions
      MYSQL_ROOT_PASSWORD: password

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  server:
    image: myapp
    container_name: myapp
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 40s

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 40s

    depends_on:
      mysqldb:
        condition: service_healthy
      server:
        condition: service_healthy