version: "3.8"
services:
  mysqldb:
    hostname: mysqldb-regions
    container_name: mysqldb-regions
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"

    logging:
      #limit logs to 200MB (4rotations of 50M each)
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: regions
      MYSQL_ROOT_PASSWORD: password

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  server:
    hostname: server-regions
    container_name: server-regions
    image: myapp
    restart: always
    logging:
      #limit logs to 200MB (4rotations of 50M each)
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"

    environment:
      REACT_APP_TOKEN: abc123

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 40s

    depends_on:
      mysqldb:
        condition: service_healthy