DROP TABLE IF EXISTS `armenia_entity`;
CREATE TABLE `armenia_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `armenia_entity` WRITE;
/*!40000 ALTER TABLE `armenia_entity` DISABLE KEYS */;
INSERT INTO `armenia_entity` (description, region) VALUES
('Yerevan (city)','01'),
('Yerevan (city)','02'),
('Yerevan (city)','03'),
('Yerevan (city)','04'),
('Yerevan (city)','05'),
('Yerevan (city)','06'),
('Yerevan (city)','07'),
('Yerevan (city)','08'),
('Yerevan (city)','09'),
('Yerevan (city)','10'),
('Yerevan (city)','11'),
('Yerevan (city)','13'),
('Yerevan (city)','19'),
('Yerevan (city)','61'),
('Yerevan (city)','62'),
('Yerevan (city)','63'),
('Yerevan (city)','64'),
('Yerevan (city)','65'),
('Yerevan (city)','66'),
('Yerevan (city)','67'),
('Yerevan (city)','68'),
('Armavir Province','12'),
('Armavir Province','27'),
('Armavir Province','28'),
('Armavir Province','29'),
('Shirak Province','14'),
('Shirak Province','45'),
('Shirak Province','46'),
('Shirak Province','47'),
('Shirak Province','48'),
('Shirak Province','49'),
('Aragatsotn Province','15'),
('Aragatsotn Province','21'),
('Aragatsotn Province','22'),
('Aragatsotn Province','23'),
('Aragatsotn Province','24'),
('Gegharkunik Province','16'),
('Gegharkunik Province','31'),
('Gegharkunik Province','32'),
('Gegharkunik Province','33'),
('Gegharkunik Province','34'),
('Gegharkunik Province','35'),
('Kotayk Province','17'),
('Kotayk Province','42'),
('Kotayk Province','43'),
('Vayots Dzor Province','18'),
('Vayots Dzor Province','56'),
('Ararat Province','25'),
('Ararat Province','26'),
('Lori Province','36'),
('Lori Province','37'),
('Lori Province','38'),
('Lori Province','39'),
('Lori Province','41'),
('Syunik Province','51'),
('Syunik Province','52'),
('Syunik Province','53'),
('Syunik Province','54'),
('Tavush Province','57'),
('Tavush Province','58'),
('Tavush Province','59'),
('Republic of Artsakh','22'),
('Republic of Artsakh(De jure part of Republic of Azerbaijan)','90'),
('Individual plates not showing province','20'),
('Individual plates not showing province','30'),
('Individual plates not showing province','40'),
('Individual plates not showing province','44'),
('Individual plates not showing province','50'),
('Individual plates not showing province','55'),
('Individual plates not showing province','60'),
('Individual plates not showing province','69'),
('Individual plates not showing province','70'),
('Individual plates not showing province','71'),
('Individual plates not showing province','72'),
('Individual plates not showing province','73'),
('Individual plates not showing province','74'),
('Individual plates not showing province','75'),
('Individual plates not showing province','76'),
('Individual plates not showing province','77'),
('Individual plates not showing province','78'),
('Individual plates not showing province','79'),
('Individual plates not showing province','80'),
('Individual plates not showing province','81'),
('Individual plates not showing province','82'),
('Individual plates not showing province','83'),
('Individual plates not showing province','84'),
('Individual plates not showing province','85'),
('Individual plates not showing province','86'),
('Individual plates not showing province','87'),
('Individual plates not showing province','88'),
('Individual plates not showing province','89'),
('Individual plates not showing province','91'),
('Individual plates not showing province','92'),
('Individual plates not showing province','93'),
('Individual plates not showing province','94'),
('Individual plates not showing province','95'),
('Individual plates not showing province','96'),
('Individual plates not showing province','97'),
('Individual plates not showing province','98'),
('Individual plates not showing province','99');
UNLOCK TABLES;

ALTER TABLE armenia_entity ADD INDEX armenia_index (description, region);



