DROP TABLE IF EXISTS `austria_entity`;

CREATE TABLE `austria_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `austria_entity` WRITE;
/*!40000 ALTER TABLE `austria_entity` DISABLE KEYS */;
INSERT INTO `austria_entity` (description, region) VALUES
('Federal official. Federal presidents plate','A'),
('Amstetten','AM'),
('Bregenz, Burgenland official','B'),
('Bad Aussee sub-district','BA'),
('Bundesbahnen (Federal Railways)','BB'),
('Kraftfahrlinien Bundesbus (Bus Service)','BD'),
('Bundesgendarmerie (Federal gendarmerie)','BG'),
('Bundesheer (Federal Army)','BH'),
('Bruck an der Leitha','BL'),
('Bruck-Mürzzuschlag','BM'),
('Baden','BN'),
('Bundespolizei (Federal police cars)','BP'),
('Braunau am Inn','BR'),
('Bludenz','BZ'),
('Deutschlandsberg','DL'),
('Dornbirn','DO'),
('Eisenstadt. Rust and Burgenland.','E'),
('Eferding','EF'),
('Eisenstadt-Umgebung.(Eisenstadt surrounding area)','EU'),
('Feldbach','FB'),
('Feldkirchen','FE'),
('Fürstenfeld','FF'),
('Feldkirch','FK'),
('Freistadt','FR'),
('Finanzverwaltung (Financial Administration)','FV'),
('Feuerwehr (Fire brigade)','FW'),
('Graz','G'),
('Gröbming sub-district','GB'),
('Gmünd','GD'),
('Gänserndorf','GF'),
('Consular corps in Styria','GK'),
('Gmunden','GM'),
('Grieskirchen','GR'),
('Güssing','GS'),
('Graz-Umgebung.(Graz surrounding area)','GU'),
('Hallein','HA'),
('Hartberg','HB'),
('Hermagor','HE'),
('Hartberg-Fürstenfeld','HF'),
('Hollabrunn','HL'),
('Horn','HO'),
('Innsbruck','I'),
('Innsbruck-Land.(Innsbruck countryside area)','IL'),
('Imst','IM'),
('Jennersdorf','JE'),
('St. Johann im Pongau','JO'),
('Judenburg','JU'),
('Justizwache (Justice police)','JW'),
('Klagenfurt','K'),
('Kitzbühel','KB'),
('Klosterneuburg','KG'),
('Kirchdorf an der Krems','KI'),
('Knittelfeld','KF'),
('Consular corps in Carinthia','KK'),
('Klagenfurt-Land','KL'),
('Korneuburg','KO'),
('Krems-Land.(Krems countryside area)','KR'),
('Krems City','KS'),
('Kufstein','KU'),
('Linz','L'),
('Landeck','LA'),
('Leibnitz','LB'),
('Leoben City','LE'),
('Lilienfeld','LF'),
('Liezen','LI'),
('Linz-Land.(Linz countryside area)','LL'),
('Leoben.(Leoben countryside area)',''),
('Lienz','LZ'),
('Mattersburg','MA'),
('Mödling','MD'),
('Melk','ME'),
('Mistelbach','MI'),
('Murtal','MT'),
('Murau','MU'),
('Mürzzuschlag','MZ'),
('Lower Austria official','N'),
('Neusiedl am See','ND'),
('Neunkirchen','NK'),
('Upper Austria official','O'),
('Oberpullendorf','OP'),
('Oberwart','OW'),
('St. Pölten','P'),
('Perg','PE'),
('St. Pölten-Land.(St. Pölten countryside area)','PL'),
('Post & Telekom Austria (Actually for postal cars only.)','PT'),
('Bad Radkersburg','RA'),
('Reutte','RE'),
('Ried im Innkreis','RI'),
('Rohrbach','RO'),
('Salzburg City and official','S'),
('Scheibbs','SB'),
('Schärding, Diplomatic corps in Salzburg','SD'),
('Steyr-Land.(Steyr countryside area)','SE'),
('Consular corps in Salzburg','SK'),
('Salzburg-Umgebung.(Salzburg countryside area)','SL'),
('Spittal an der Drau','SP'),
('Südoststeiermark','SO'),
('Steyr City','SR'),
('Styria official','ST'),
('St. Veit an der Glan','SV'),
('Schwechat City','SW'),
('Schwaz','SZ'),
('Tirol official','T'),
('Tamsweg','TA'),
('Diplomatic corps in Tirol','TD'),
('Consular corps in Tirol','TK'),
('Tulln','TU'),
('Urfahr-Umgebung','UU'),
('Vorarlberg official','V'),
('Vöcklabruck','VB'),
('Diplomatic corps in Vorarlberg','VD'),
('Villach City','VI'),
('Völkermarkt, Consular corps in Vorarlberg','VK'),
('Villach-Land.(Villach countryside area)','VL'),
('Voitsberg','VO'),
('Vienna (Wien)','W'),
('Wiener Neustadt-Land.(Wiener Neustadt countryside area)','WB'),
('Diplomatic corps in Vienna','WD'),
('Consular corps in Vienna','WK'),
('Wels City','WE'),
('Wels-Land.(Wels countryside area)','WL'),
('Wiener Neustadt City','WN'),
('Wolfsberg','WO'),
('Waidhofen an der Thaya','WT'),
('Wien-Umgebung.(Vienna surrounding area)','WU'),
('Waidhofen an der Ybbs','WY'),
('Weiz','WZ'),
('Zell am See','ZE'),
('Zwettl','ZT'),
('Zollwache (Zollwache merged with federal police)','ZW');
UNLOCK TABLES;

ALTER TABLE austria_entity ADD INDEX austria_index (description, region);