DROP TABLE IF EXISTS `british_entity`;
CREATE TABLE `british_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `british_entity` WRITE;
/*!40000 ALTER TABLE `british_entity` DISABLE KEYS */;
INSERT INTO `british_entity` (description, region) VALUES
('Anglia','A'),
('Anglia, Peterborough','AA'),
('Anglia, Peterborough','AB'),
('Anglia, Peterborough','AC'),
('Anglia, Peterborough','AD'),
('Anglia, Peterborough','AE'),
('Anglia, Peterborough','AF'),
('Anglia, Peterborough','AG'),
('Anglia, Peterborough','AJ'),
('Anglia, Peterborough','AK'),
('Anglia, Peterborough','AM'),
('Anglia, Peterborough','AN'),
('Anglia','AH'),
('Anglia','AL'),
('Anglia, Norwich','AO'),
('Anglia, Norwich','AP'),
('Anglia, Norwich','AR'),
('Anglia, Norwich','AS'),
('Anglia, Norwich','AT'),
('Anglia, Norwich','AU'),
('Anglia, Ipswich','AV'),
('Anglia, Ipswich','AW'),
('Anglia, Ipswich','AX'),
('Anglia, Ipswich','AY'),
('Birmingham','B'),
('Birmingham, Birmingham','BA'),
('Birmingham, Birmingham','BB'),
('Birmingham, Birmingham','BC'),
('Birmingham, Birmingham','BD'),
('Birmingham, Birmingham','BE'),
('Birmingham, Birmingham','BF'),
('Birmingham, Birmingham','BG'),
('Birmingham, Birmingham','BH'),
('Birmingham, Birmingham','BJ'),
('Birmingham, Birmingham','BK'),
('Birmingham, Birmingham','BL'),
('Birmingham, Birmingham','BM'),
('Birmingham, Birmingham','BN'),
('Birmingham, Birmingham','BO'),
('Birmingham, Birmingham','BP'),
('Birmingham, Birmingham','BR'),
('Birmingham, Birmingham','BS'),
('Birmingham, Birmingham','BT'),
('Birmingham, Birmingham','BU'),
('Birmingham, Birmingham','BV'),
('Birmingham, Birmingham','BW'),
('Birmingham, Birmingham','BX'),
('Birmingham','BY'),
('Cymru (Wales)','C'),
('Cymru (Wales), Cardiff','CA'),
('Cymru (Wales), Cardiff','CB'),
('Cymru (Wales), Cardiff','CC'),
('Cymru (Wales), Cardiff','CD'),
('Cymru (Wales), Cardiff','CE'),
('Cymru (Wales), Cardiff','CF'),
('Cymru (Wales), Cardiff','CG'),
('Cymru (Wales), Cardiff','CH'),
('Cymru (Wales), Cardiff','CJ'),
('Cymru (Wales), Cardiff','CK'),
('Cymru (Wales), Cardiff','CL'),
('Cymru (Wales), Cardiff','CM'),
('Cymru (Wales), Cardiff','CN'),
('Cymru (Wales), Cardiff','CO'),
('Cymru (Wales), Swansea','CP'),
('Cymru (Wales), Swansea','CR'),
('Cymru (Wales), Swansea','CS'),
('Cymru (Wales), Swansea','CT'),
('Cymru (Wales), Swansea','CU'),
('Cymru (Wales), Swansea','CV'),
('Cymru (Wales), Bangor','CW'),
('Cymru (Wales), Bangor','CX'),
('Cymru (Wales), Bangor','CY'),
('Deeside','D'),
('Deeside, Chester','DA'),
('Deeside, Chester','DB'),
('Deeside, Chester','DC'),
('Deeside, Chester','DD'),
('Deeside, Chester','DE'),
('Deeside, Chester','DF'),
('Deeside, Chester','DG'),
('Deeside, Chester','DH'),
('Deeside, Chester','DJ'),
('Deeside, Chester','DK'),
('Deeside, Shrewsbury','DL'),
('Deeside, Shrewsbury','DM'),
('Deeside, Shrewsbury','DN'),
('Deeside, Shrewsbury','DO'),
('Deeside, Shrewsbury','DP'),
('Deeside, Shrewsbury','DS'),
('Deeside, Shrewsbury','DT'),
('Deeside, Shrewsbury','DU'),
('Deeside, Shrewsbury','DV'),
('Deeside, Shrewsbury','DW'),
('Deeside, Shrewsbury','DX'),
('Deeside, Shrewsbury','DY'),
('Deeside','DR'),
('Essex','E'),
('Essex, Chelmsford','EA'),
('Essex, Chelmsford','EB'),
('Essex, Chelmsford','EC'),
('Essex, Chelmsford','EE'),
('Essex, Chelmsford','EF'),
('Essex, Chelmsford','EG'),
('Essex, Chelmsford','EJ'),
('Essex, Chelmsford','EK'),
('Essex, Chelmsford','EL'),
('Essex, Chelmsford','EM'),
('Essex, Chelmsford','EN'),
('Essex, Chelmsford','EO'),
('Essex, Chelmsford','EP'),
('Essex, Chelmsford','ER'),
('Essex, Chelmsford','ES'),
('Essex, Chelmsford','ET'),
('Essex, Chelmsford','EU'),
('Essex, Chelmsford','EV'),
('Essex, Chelmsford','EW'),
('Essex, Chelmsford','EX'),
('Essex, Chelmsford','EY'),
('Essex','ED'),
('Essex','EH'),
('Forest and Fens','F'),
('Forest and Fens, Nottingham','FA'),
('Forest and Fens, Nottingham','FB'),
('Forest and Fens, Nottingham','FC'),
('Forest and Fens, Nottingham','FD'),
('Forest and Fens, Nottingham','FE'),
('Forest and Fens, Nottingham','FF'),
('Forest and Fens, Nottingham','FG'),
('Forest and Fens, Nottingham','FH'),
('Forest and Fens, Nottingham','FJ'),
('Forest and Fens, Nottingham','FK'),
('Forest and Fens, Nottingham','FL'),
('Forest and Fens, Nottingham','FM'),
('Forest and Fens, Nottingham','FN'),
('Forest and Fens, Nottingham','FP'),
('Forest and Fens','FO'),
('Forest and Fens','FU'),
('Forest and Fens, Lincoln','FR'),
('Forest and Fens, Lincoln','FS'),
('Forest and Fens, Lincoln','FT'),
('Forest and Fens, Lincoln','FV'),
('Forest and Fens, Lincoln','FW'),
('Forest and Fens, Lincoln','FX'),
('Forest and Fens, Lincoln','FY'),
('Garden of England','G'),
('Garden of England, Maidstone','GA'),
('Garden of England, Maidstone','GB'),
('Garden of England, Maidstone','GC'),
('Garden of England, Maidstone','GD'),
('Garden of England, Maidstone','GE'),
('Garden of England, Maidstone','GF'),
('Garden of England, Maidstone','GG'),
('Garden of England, Maidstone','GH'),
('Garden of England, Maidstone','GJ'),
('Garden of England, Maidstone','GK'),
('Garden of England, Maidstone','GL'),
('Garden of England, Maidstone','GM'),
('Garden of England, Maidstone','GN'),
('Garden of England','GO'),
('Garden of England, Brighton','GP'),
('Garden of England, Brighton','GR'),
('Garden of England, Brighton','GS'),
('Garden of England, Brighton','GT'),
('Garden of England, Brighton','GU'),
('Garden of England, Brighton','GW'),
('Garden of England, Brighton','GX'),
('Garden of England, Brighton','GY'),
('Hampshire and Dorset','H'),
('Hampshire and Dorset, Bournemouth','HA'),
('Hampshire and Dorset, Bournemouth','HB'),
('Hampshire and Dorset, Bournemouth','HC'),
('Hampshire and Dorset, Bournemouth','HD'),
('Hampshire and Dorset, Bournemouth','HE'),
('Hampshire and Dorset, Bournemouth','HF'),
('Hampshire and Dorset, Bournemouth','HG'),
('Hampshire and Dorset, Bournemouth','HH'),
('Hampshire and Dorset, Bournemouth','HJ'),
('Hampshire and Dorset, Portsmouth','HK'),
('Hampshire and Dorset, Portsmouth','HL'),
('Hampshire and Dorset, Portsmouth','HM'),
('Hampshire and Dorset, Portsmouth','HN'),
('Hampshire and Dorset, Portsmouth','HP'),
('Hampshire and Dorset, Portsmouth','HR'),
('Hampshire and Dorset, Portsmouth','HS'),
('Hampshire and Dorset, Portsmouth','HT'),
('Hampshire and Dorset, Portsmouth','HU'),
('Hampshire and Dorset, Portsmouth','HV'),
('Hampshire and Dorset, Portsmouth','HX'),
('Hampshire and Dorset, Portsmouth','HY'),
('Hampshire and Dorset','HO'),
('Hampshire and Dorset, Isle of Wight','HW'),
('Borehamwood','K'),
('Borehamwood','KA'),
('Borehamwood','KB'),
('Borehamwood','KC'),
('Borehamwood','KD'),
('Borehamwood','KE'),
('Borehamwood','KF'),
('Borehamwood','KG'),
('Borehamwood','KH'),
('Borehamwood','KJ'),
('Borehamwood','KK'),
('Borehamwood','KL'),
('Northampton','KM'),
('Northampton','KN'),
('Northampton','KO'),
('Northampton','KP'),
('Northampton','KR'),
('Northampton','KS'),
('Northampton','KT'),
('Northampton','KU'),
('Northampton','KV'),
('Northampton','KW'),
('Northampton','KX'),
('Northampton','KY'),
('London','L'),
('London, Wimbledon','LA'),
('London, Wimbledon','LB'),
('London, Wimbledon','LC'),
('London, Wimbledon','LD'),
('London, Wimbledon','LE'),
('London, Wimbledon','LF'),
('London, Wimbledon','LG'),
('London, Wimbledon','LH'),
('London, Wimbledon','LJ'),
('London, Borehamwood (formerly Stanmore)','LK'),
('London, Borehamwood (formerly Stanmore)','LL'),
('London, Borehamwood (formerly Stanmore)','LM'),
('London, Borehamwood (formerly Stanmore)','LN'),
('London, Borehamwood (formerly Stanmore)','LO'),
('London, Borehamwood (formerly Stanmore)','LP'),
('London, Borehamwood (formerly Stanmore)','LR'),
('London, Borehamwood (formerly Stanmore)','LS'),
('London, Borehamwood (formerly Stanmore)','LT'),
('London, Sidcup','LU'),
('London, Sidcup','LV'),
('London, Sidcup','LW'),
('London, Sidcup','LX'),
('London, Sidcup','LY'),
('Manchester and Merseyside','M'),
('Manchester and Merseyside, Manchester','MA'),
('Manchester and Merseyside, Manchester','MB'),
('Manchester and Merseyside, Manchester','MC'),
('Manchester and Merseyside, Manchester','MD'),
('Manchester and Merseyside, Manchester','ME'),
('Manchester and Merseyside, Manchester','MF'),
('Manchester and Merseyside, Manchester','MG'),
('Manchester and Merseyside, Manchester','MH'),
('Manchester and Merseyside, Manchester','MJ'),
('Manchester and Merseyside, Manchester','MK'),
('Manchester and Merseyside, Manchester','ML'),
('Manchester and Merseyside, Manchester','MM'),
('Manchester and Merseyside, Manchester','MP'),
('Manchester and Merseyside, Manchester','MT'),
('Manchester and Merseyside, Manchester','MU'),
('Manchester and Merseyside, Manchester','MV'),
('Manchester and Merseyside, Manchester','MW'),
('Manchester and Merseyside, Manchester','MX'),
('Manchester and Merseyside, Isle of Man','MN'),
('Manchester and Merseyside','MO'),
('Manchester and Merseyside','MR'),
('Manchester and Merseyside','MS'),
('Manchester and Merseyside','MY'),
('Newcastle','N'),
('Newcastle, Newcastle','NA'),
('Newcastle, Newcastle','NB'),
('Newcastle, Newcastle','NC'),
('Newcastle, Newcastle','ND'),
('Newcastle, Newcastle','NE'),
('Newcastle, Newcastle','NF'),
('Newcastle, Newcastle','NG'),
('Newcastle, Newcastle','NH'),
('Newcastle, Newcastle','NJ'),
('Newcastle, Newcastle','NK'),
('Newcastle, Newcastle','NL'),
('Newcastle, Newcastle','NM'),
('Newcastle, Newcastle','NN'),
('Newcastle, Newcastle','NO'),
('Newcastle, Stockton','NP'),
('Newcastle, Stockton','NR'),
('Newcastle, Stockton','NS'),
('Newcastle, Stockton','NT'),
('Newcastle, Stockton','NU'),
('Newcastle, Stockton','NV'),
('Newcastle, Stockton','NW'),
('Newcastle, Stockton','NX'),
('Newcastle, Stockton','NY'),
('Oxford','O'),
('Oxford, Oxford','OA'),
('Oxford, Oxford','OB'),
('Oxford, Oxford','OC'),
('Oxford, Oxford','OD'),
('Oxford, Oxford','OE'),
('Oxford, Oxford','OF'),
('Oxford, Oxford','OG'),
('Oxford, Oxford','OH'),
('Oxford, Oxford','OJ'),
('Oxford, Oxford','OL'),
('Oxford, Oxford','OM'),
('Oxford, Oxford','OO'),
('Oxford, Oxford','OP'),
('Oxford, Oxford','OT'),
('Oxford, Oxford','OU'),
('Oxford, Oxford','OV'),
('Oxford, Oxford','OW'),
('Oxford, Oxford','OX'),
('Oxford, Oxford','OY'),
('Oxford','OK'),
('Oxford','ON'),
('Oxford','OR'),
('Oxford','OS'),
('Preston','P'),
('Preston, Preston','PA'),
('Preston, Preston','PB'),
('Preston, Preston','PC'),
('Preston, Preston','PD'),
('Preston, Preston','PE'),
('Preston, Preston','PF'),
('Preston, Preston','PG'),
('Preston, Preston','PH'),
('Preston, Preston','PJ'),
('Preston, Preston','PK'),
('Preston, Preston','PL'),
('Preston, Preston','PM'),
('Preston, Preston','PN'),
('Preston, Preston','PO'),
('Preston, Preston','PP'),
('Preston, Preston','PR'),
('Preston, Preston','PS'),
('Preston, Preston','PT'),
('Preston, Carlisle','PU'),
('Preston, Carlisle','PV'),
('Preston, Carlisle','PW'),
('Preston, Carlisle','PX'),
('Preston, Carlisle','PY'),
('Reading','R'),
('Reading, Reading','RA'),
('Reading, Reading','RB'),
('Reading, Reading','RC'),
('Reading, Reading','RD'),
('Reading, Reading','RE'),
('Reading, Reading','RF'),
('Reading, Reading','RG'),
('Reading, Reading','RH'),
('Reading, Reading','RJ'),
('Reading, Reading','RK'),
('Reading, Reading','RL'),
('Reading, Reading','RM'),
('Reading, Reading','RN'),
('Reading, Reading','RO'),
('Reading, Reading','RP'),
('Reading, Reading','RR'),
('Reading, Reading','RS'),
('Reading, Reading','RT'),
('Reading, Reading','RV'),
('Reading, Reading','RW'),
('Reading, Reading','RX'),
('Reading, Reading','RY'),
('Reading','RU'),
('Scotland','S'),
('Scotland, Glasgow','SA'),
('Scotland, Glasgow','SB'),
('Scotland, Glasgow','SC'),
('Scotland, Glasgow','SD'),
('Scotland, Glasgow','SE'),
('Scotland, Glasgow','SF'),
('Scotland, Glasgow','SG'),
('Scotland, Glasgow','SH'),
('Scotland, Glasgow','SJ'),
('Scotland, Edinburgh','SK'),
('Scotland, Edinburgh','SL'),
('Scotland, Edinburgh','SM'),
('Scotland, Edinburgh','SN'),
('Scotland, Edinburgh','SO'),
('Scotland, Dundee','SP'),
('Scotland, Dundee','SR'),
('Scotland, Dundee','SS'),
('Scotland, Dundee','ST'),
('Scotland','SU'),
('Scotland, Aberdeen','SV'),
('Scotland, Aberdeen','SW'),
('Scotland, Inverness','SX'),
('Scotland, Inverness','SY'),
('Severn Valley','V'),
('Severn Valley, Worcester','VA'),
('Severn Valley, Worcester','VB'),
('Severn Valley, Worcester','VC'),
('Severn Valley, Worcester','VE'),
('Severn Valley, Worcester','VF'),
('Severn Valley, Worcester','VG'),
('Severn Valley, Worcester','VH'),
('Severn Valley, Worcester','VJ'),
('Severn Valley, Worcester','VK'),
('Severn Valley, Worcester','VL'),
('Severn Valley, Worcester','VM'),
('Severn Valley, Worcester','VN'),
('Severn Valley, Worcester','VO'),
('Severn Valley, Worcester','VP'),
('Severn Valley, Worcester','VR'),
('Severn Valley, Worcester','VS'),
('Severn Valley, Worcester','VT'),
('Severn Valley, Worcester','VU'),
('Severn Valley, Worcester','VV'),
('Severn Valley, Worcester','VX'),
('Severn Valley, Worcester','VY'),
('Severn Valley','VD'),
('Severn Valley','VW'),
('West of England','W'),
('West of England, Exeter','WA'),
('West of England, Exeter','WB'),
('West of England, Exeter','WD'),
('West of England, Exeter','WE'),
('West of England, Exeter','WF'),
('West of England, Exeter','WG'),
('West of England, Exeter','WH'),
('West of England, Exeter','WJ'),
('West of England','WC'),
('West of England, Truro','WK'),
('West of England, Truro','WL'),
('West of England, Bristol','WM'),
('West of England, Bristol','WN'),
('West of England, Bristol','WO'),
('West of England, Bristol','WP'),
('West of England, Bristol','WR'),
('West of England, Bristol','WS'),
('West of England, Bristol','WT'),
('West of England, Bristol','WU'),
('West of England, Bristol','WV'),
('West of England, Bristol','WW'),
('West of England, Bristol','WX'),
('West of England, Bristol','WY'),
('Personal export, March/September issue','XA'),
('Personal export, April/October issue','XB'),
('Personal export, May/November issue','XC'),
('Personal export, June/December issue','XD'),
('Personal export, July/January issue','XE'),
('Personal export, August/February issue','XF'),
('Personal export','XG'),
('Personal export','XH'),
('Personal export','XJ'),
('Personal export','XK'),
('Personal export','XL'),
('Personal export','XM'),
('Personal export','XN'),
('Personal export','XO'),
('Personal export','XP'),
('Personal export','XR'),
('Personal export','XS'),
('Personal export','XT'),
('Personal export','XU'),
('Personal export','XV'),
('Personal export','XW'),
('Personal export','XX'),
('Personal export','XY'),
('Yorkshire','Y'),
('Yorkshire, Leeds','YA'),
('Yorkshire, Leeds','YB'),
('Yorkshire, Leeds','YC'),
('Yorkshire, Leeds','YD'),
('Yorkshire, Leeds','YE'),
('Yorkshire, Leeds','YF'),
('Yorkshire, Leeds','YG'),
('Yorkshire, Leeds','YH'),
('Yorkshire, Leeds','YJ'),
('Yorkshire, Leeds','YK'),
('Yorkshire, Leeds','YL'),
('Yorkshire, Sheffield','YM'),
('Yorkshire, Sheffield','YN'),
('Yorkshire, Sheffield','YO'),
('Yorkshire, Sheffield','YP'),
('Yorkshire, Sheffield','YR'),
('Yorkshire, Sheffield','YS'),
('Yorkshire, Sheffield','YT'),
('Yorkshire, Sheffield','YU'),
('Yorkshire, Sheffield','YV'),
('Yorkshire, Beverley','YW'),
('Yorkshire, Beverley','YX'),
('Yorkshire, Beverley','YY');
UNLOCK TABLES;

ALTER TABLE british_entity ADD INDEX british_index (description, region);