DROP TABLE IF EXISTS `france_entity`;

CREATE TABLE `france_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `france_entity` WRITE;
/*!40000 ALTER TABLE `france_entity` DISABLE KEYS */;
INSERT INTO `france_entity` (description, region) VALUES
('Ain,LaonBourg-en-Bresse,Auvergne-Rhône-Alpes','01'),
('Aisne,Laon,Hauts-de-France','02'),
('Allier,Moulins,Auvergne-Rhône-Alpes','03'),
('Alpes-de-Haute-Provence,Digne-les-Bains,Provence-Alpes-Côte d\'Azur','04'),
('Hautes-Alpes,Gap,Provence-Alpes-Côte d\'Azur','05'),
('Alpes-Maritimes,Nice,Provence-Alpes-Côte d\'Azur','06'),
('Ardèche,Privas,Auvergne-Rhône-Alpes','07'),
('Ardennes,Charleville-Mézières,Grand Est','08'),
('Ariège,Foix,Occitanie','09'),
('Aube,Troyes,Grand Est','10'),
('Aude,Carcassonne,Occitanie','11'),
('Aveyron,Rodez,Occitanie','12'),
('Bouches-du-Rhône,Marseille,Provence-Alpes-Côte d\'Azur','13'),
('Calvados,Caen,Normandie','14'),
('Cantal,Aurillac,Auvergne-Rhône-Alpes','15'),
('Charente,Angoulême,Nouvelle-Aquitaine','16'),
('Charente-Maritime,La Rochelle,Nouvelle-Aquitaine','17'),
('Cher,Bourges,Centre-Val de Loire','18'),
('Corrèze,Tulle,Nouvelle-Aquitaine','19'),
('Corse-du-Sud,Ajaccio,Corse','2A'),
('Haute-Corse,Bastia,Corse','2B'),
('Côte-d\'Or,Dijon,Bourgogne-Franche-Comté','21'),
('Côtes-d\'Armor,Saint-Brieuc,Bretagne','22'),
('Creuse,Guéret,Nouvelle-Aquitaine','23'),
('Dordogne,Périgueux,Nouvelle-Aquitaine','24'),
('Doubs,Besançon,Bourgogne-Franche-Comté	','25'),
('Drôme,Valence,Auvergne-Rhône-Alpes','26'),
('Eure,Évreux,Normandie','27'),
('Eure-et-Loir,Chartres,Centre-Val de Loire','28'),
('Finistère,Quimper,Bretagne','29'),
('Gard,Nîmes,Occitanie','30'),
('Haute-Garonne,Toulouse,Occitanie','31'),
('Gers,Auch,Occitanie','32'),
('Gironde,Bordeaux,Nouvelle-Aquitaine','33'),
('Hérault,Montpellier,Occitanie','34'),
('Ille-et-Vilaine,Rennes,Bretagne','35'),
('Indre,Châteauroux,Centre-Val de Loire','36'),
('Indre-et-Loire,Tours,Centre-Val de Loire','37'),
('Isère,Grenoble,Auvergne-Rhône-Alpes','38'),
('Jura,Lons-le-Saunier,Bourgogne-Franche-Comté','39'),
('Landes,Mont-de-Marsan,Nouvelle-Aquitaine','40'),
('Loir-et-Cher,Blois,Centre-Val de Loire','41'),
('Loire,Saint-Étienne,Auvergne-Rhône-Alpes','42'),
('Haute-Loire,Le Puy,Auvergne-Rhône-Alpes','43'),
('Loire-Atlantique,Nantes,Pays de la Loire','44'),
('Loiret,Orléans,Centre-Val de Loire','45'),
('Lot,Cahors,Occitanie','46'),
('Lot-et-Garonne,Agen,Nouvelle-Aquitaine','47'),
('Lozère,Mende,Occitanie','48'),
('Maine-et-Loire,Angers,Pays de la Loire','49'),
('Manche,Saint-Lô,Normandie','50'),
('Marne,Châlons-en-Champagne,Grand Est','51'),
('Haute-Marne,Chaumont,Grand Est','52'),
('Mayenne,Laval,Pays de la Loire','53'),
('Meurthe-et-Moselle,Nancy,Grand Est','54'),
('Meuse,Bar-le-Duc,Grand Est','55'),
('Morbihan,Vannes,Bretagne','56'),
('Moselle,Metz,Grand Est','57'),
('Nièvre,Nevers,Bourgogne-Franche-Comté	','58'),
('Nord,Lille,Hauts-de-France','59'),
('Oise,Beauvais,Hauts-de-France','60'),
('Orne,Alençon,Normandie','61'),
('Pas-de-Calais,Arras,Hauts-de-France','62'),
('Puy-de-Dôme,Clermont-Ferrand,Auvergne-Rhône-Alpes','63'),
('Pyrénées-Atlantiques,Pau,Nouvelle-Aquitaine','64'),
('Hautes-Pyrénées,Tarbes,Occitanie','65'),
('Pyrénées-Orientales,Perpignan,Occitanie','66'),
('Bas-Rhin,Strasbourg,Grand Est','67'),
('Haut-Rhin,Colmar,Grand Est','68'),
('Rhône,Lyon,Auvergne-Rhône-Alpes','69D'),
('Métropolede Lyon,Lyon,Auvergne-Rhône-Alpes','69M'),
('Haute-Saône,Vesoul,Bourgogne-Franche-Comté','70'),
('Saône-et-Loire,Mâcon,Bourgogne-Franche-Comté','71'),
('Sarthe,Le Mans,Pays de la Loire','72'),
('Savoie,Chambéry,Auvergne-Rhône-Alpes','73'),
('Haute-Savoie,Annecy,Auvergne-Rhône-Alpes','74'),
('Paris,Paris,Île-de-France','75'),
('Seine-Maritime,Rouen,Normandie','76'),
('Seine-et-Marne,Melun,Île-de-France','77'),
('Yvelines,Versailles,Île-de-France','78'),
('Deux-Sèvres,Niort,Nouvelle-Aquitaine','79'),
('Somme,Amiens,Hauts-de-France','80'),
('Tarn,Albi,Occitanie','81'),
('Tarn-et-Garonne,Montauban,Occitanie','82'),
('Var,Toulon,Provence-Alpes-Côte d\'Azur	','83'),
('Vaucluse,Avignon,Provence-Alpes-Côte d\'Azur	','84'),
('Vendée,La Roche-sur-Yon,Pays de la Loire','85'),
('Vienne,Poitiers,Nouvelle-Aquitaine','86'),
('Haute-Vienne,Limoges,Nouvelle-Aquitaine','87'),
('Vosges,Épinal,Grand Est','88'),
('Yonne	Auxerre	Bourgogne-Franche-Comté	','89'),
('Territoire-de-Belfort,Belfort,Bourgogne-Franche-Comté	','90'),
('Essonne,Évry,Île-de-France','91'),
('Hauts-de-Seine,Nanterre,Île-de-France','92'),
('Seine-Saint-Denis,Bobigny,Île-de-France','93'),
('Val-de-Marne,Créteil,Île-de-France','94'),
('Val-d\'Oise,Pontoise,Île-de-France','95'),
('Guadeloupe,Basse-Terre,Outre-Mer','971'),
('Martinique,Fort-de-France,Outre-Mer','972'),
('Guyane française,Cayenne,Outre-Mer','973'),
('Réunion,Saint-Denis,Outre-Mer','974'),
('Mayotte,Mamoudzou,Outre-Mer','976');
UNLOCK TABLES;

ALTER TABLE france_entity ADD INDEX france_index (description, region);