DROP TABLE IF EXISTS `germany_entity`;

CREATE TABLE `germany_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `germany_entity` WRITE;
/*!40000 ALTER TABLE `german_entity` DISABLE KEYS */;
INSERT INTO `germany_entity` (description, region) VALUES
('Augsburg, Bavaria','A'),
('Aalen & Ostalbkreis, Baden-Württemberg','AA'),
('Aschaffenburg, Bavaria','AB'),
('Altenburger Land, Thuringia','ABG'),
('Aachen, North-Rhine-Westphalia','AC'),
('Ahaus, North-Rhine-Westphalia','AH'),
('Bad Aibling, Bavaria','AIB'),
('Aichach-Friedberg, Bavaria','AIC'),
('Auerbach, Saxony','AE'),
('Altenkirchen (Westerwald), Rhineland Palatinate','AK'),
('Altena, North-Rhine-Westphalia','AL'),
('Alfeld, Lower Saxony','ALF'),
('Alsfeld, Hesse','ALS'),
('Alzenau, Bavaria','ALZ'),
('Amberg, Bavaria','AM'),
('Ansbach, Bavaria','AN'),
('Annaberg-Buchholz, Saxony','ANA'),
('Angermünde, Brandenburg','ANG'),
('Anklam, Mecklenburg-Vorpommern','ANK'),
('Altötting, Bavaria','AO'),
('Apolda & Weimarer Land, Thuringia','AP'),
('Apolda, Thuringia','APD'),
('Arnsberg, North-Rhine-Westphalia','AR'),
('Arnstadt, Thuringia','ARN'),
('Artern, Thuringia','ART'),
('Amberg-Sulzbach, Bavaria','AS'),
('Aschendorf, Lower Saxony','ASD'),
('Aschersleben-Staßfurter Landkreis, Saxony-Anhalt','ASL'),
('Aue-Schwarzenberg, Saxony','ASZ'),
('Alten-Treptow, Mecklenburg-Vorpommern','AT'),
('Aue, Saxony','AU'),
('Aurich, Lower Saxony','AUR'),
('Ahrweiler, Rhineland Palatinate','AW'),
('Alzey-Worms, Rhineland Palatinate','AZ'),
('Anhalt-Zerbst, Saxony-Anhalt','AZE'),
('Berlin','B'),
('Bamberg, Bavaria','BA'),
('Baden-Baden, Baden-Württemberg','BAD'),
('Barnim (Eberswalde), Brandenburg','BAR'),
('Böblingen, Baden-Württemberg','BB'),
('Bernburg, Saxony-Anhalt','BBG'),
('Brandenburg Land official vehicles','BBL'),
('Biberach, Baden-Württemberg','BC'),
('Buchen, Baden-Württemberg','BCH'),
('Federal German government vehicles','BD'),
('Bechum, North-Rhine-Westphalia','BE'),
('Brand-Erbisdorf, Saxony','BED'),
('Beilingries, Bavaria','BEI'),
('Blezig, Brandenburg','BEL'),
('Bernau, Brandenburg','BER'),
('Burgsteinfurt, North-Rhine-Westphalia','BF'),
('Border police vehicles','BG'),
('Berchtesgaden, Bavaria','BGD'),
('Berchtesgardener Land, Bavaria','BGL'),
('Bühl, Baden-Württenmberg','BH'),
('Bielefeld, North-Rhine-Westphalia','BI'),
('Biedenkopf, Hesse','BID'),
('Bingen, Rhineland Palatinate','BIN'),
('Birkenfeld, Rhineland Palatinate','BIR'),
('Bitburg-Prüm, Rhineland Palatinate','BIT'),
('Bischofswerda, Saxony','BIW'),
('Bicknang, Baden-Württemberg','BK'),
('Bernkastel, Rhineland Palatinate','BKS'),
('Balingen & Zollernalbkreis, Baden-Württemberg','BL'),
('Bad Berleburg, North-Rhine-Westphalia','BLB'),
('Burgenlandkreis, Saxony-Anhalt','BLK'),
('Bergheim & Erftkreis, North-Rhine-Westphalia','BM'),
('Bonn, North-Rhine-Westphalia','BN'),
('Borna, Saxony','BNA'),
('Bochum, North-Rhine-Westphalia','BO'),
('Bördekreis, Saxony-Anhalt','BÖ'),
('Bogen, Bavaria','BOG'),
('Bocholt, North-Rhine-Westphalia','BOH'),
('Borken, North-Rhine-Westphalia','BOR'),
('Bottrop, North-Rhine-Westphalia','BOT'),
('Postal authority vehicles (Bundespost)','BP'),
('Bruchsal, Baden-Württemberg','BR'),
('Brake (Unterweser) & Wesermarsch, Lower Saxony','BRA'),
('Brandenburg, Brandenburg','BRB'),
('Burg, Saxony-Anhalt','BRG'),
('Brilon, North-Rhine-Westphalia','BRI'),
('Bad Brückenau, Bavaria','BRK'),
('Braunlage, Lower Saxony','BRL'),
('Bremervörde, Lower Saxony','BRV'),
('Brunswick (Braunschweig), Lower Saxony','BS'),
('Bersenbrück, Lower Saxony','BSB'),
('Beeskow, Brandenburg','BSK'),
('Bayreuth, Bavaria','BT'),
('Bitterfeld, Saxony-Anhalt','BTF'),
('Burgdorf, Lower Saxony','BU'),
('Büdingen, Hesse','BÜD'),
('Burglengenfeld, Bavaria','BUL'),
('Buren, North-Rhine-Westphalia','BUR'),
('Büsingen & Konstanz, Baden-Württemberg','BÜS'),
('Bützow, Mecklenburg-Vorpommern','BÜZ'),
('Maritime authority vehicles','BW'),
('Badem-Württemberg Land official vehicles','BWL'),
('Bavaria State (Bayern Land) official vehicles','BYL'),
('Bautzen, Saxony','BZ'),
('Bergzabern, Rhineland Palatinate','BZA'),
('Chemnitz, Saxony','C'),
('Calau, Brandenburg','CA'),
('Castrop-Rauxel, North-Rhine-Westphalia','CAS'),
('Cottbus, Brandenburg','CB'),
('Celle, Lower Saxony','CE'),
('Cham, Bavaria','CHA'),
('Chemnitzer Land, Kreis Glochau, Saxony','CHL'),
('Cloppenburg, Lower Saxony','CLP'),
('Clausthal-Zellerfeld, Lower Saxony','CLZ'),
('Coburg, Bavaria','CO'),
('Cochem-Zell, Rhineland Palatinate','COC'),
('Coesfeld, North-Rhine-Westphalia','COE'),
('Crailsheim, Baden-Württemberg','CR'),
('Cottbus, Saxony','CT'),
('Cuxhaven, Lower Saxony','CUX'),
('Calw, Baden-Württemberg','CW'),
('Düsseldorf, North-Rhine-Westphalia','D'),
('Darmstadt & Darmstadt-Dieburg, Hesse','DA'),
('Dachau, Bavaria','DAH'),
('Lüchow-Dannenberg, Lower Saxony','DAN'),
('Daun, Rhineland Palatinate','DAU'),
('Rail authority vehicles (Deutsche Bundesbahn)','DB'),
('Bad Doberan, Mecklenburg-Vorpommern','DBR'),
('Dresden','DD'),
('Dessau, Saxony-Anhalt','DE'),
('Deggendorf, Bavaria','DEG'),
('Delmenhorst, Lower Saxony','DEL'),
('Donaueschingen, Baden-Württemberg','DG'),
('Dingolfing-Landau, Bavaria','DGF'),
('Diepholz, Lower Saxony','DH'),
('Dieburg, Hesse','DI'),
('Dillenburg, Hesse','DIL'),
('Dinslaken, North-Rhine-Westphalia','DIN'),
('Diez, Rhineland Palatinate','DIZ'),
('Dinkelsbühl, Bavaria','DKB'),
('Döbeln, Saxony','DL'),
('Dillingen an der Donau, Bavaria','DLG'),
('Demmin, Mecklenburg-Vorpommern','DM'),
('Düren, North-Rhine-Westphalia','DN'),
('Dortmund, North-Rhine-Westphalia','DO'),
('Donau-Ries, Bavaria','DON'),
('Donaueschingen, Baden-Württemberg','DS'),
('Detmold & Lippe, North-Rhine-Westphalia','DT'),
('Duisburg, North-Rhine-Westphalia','DU'),
('Duderstadt, Lower Saxony','DUD'),
('Bad Dürkheim & Weinstraße, Rhineland Palatinate','DÜW'),
('Dippoldiswalde & Weißeritzkreis, Saxony','DW'),
('Delitzsch, Saxony','DZ'),
('Essen, North-Rhine-Westphalia','E'),
('Eisenach, Thuringia','EA'),
('Eilenburg, Saxony','EB'),
('Ebersberg, Bavaria','EBE'),
('Ebern, Bavaria','EBN'),
('Ebermannstadt, Bavaria','EBS'),
('Eckernförde, Schleswig-Holstein','ECK'),
('Erding, Bavaria','ED'),
('Elbe-Elster, Brandenburg','EE'),
('Erfurt, Thuringia','EF'),
('Eggenfelden, Bavaria','EG'),
('Eisenhüttenstadt, Brandenburg','EH'),
('Ehingen, Baden-Württemberg','EHI'),
('Eichstätt, Bavaria','EI'),
('Eichsfeld, Thuringia','EIC'),
('Eichstätt, Bavaria','EIH'),
('Eisleben, Saxony-Anhalt','EIL'),
('Einbeck, Lower Saxony','EIN'),
('Eisenberg','EIS'),
('Emsland, Lower Saxony','EL'),
('Emmendingen, Baden-Württemberg','EM'),
('Emden, Lower Saxony','EMD'),
('Bad Ems & Rhein-Lahn-Kreis, Rhineland Palatinate','EMS'),
('Ennepe-Ruhr-Kreis, North-Rhine-Westphalia','EN'),
('Erlangen, Bavaria','ER'),
('Erbach & Oldenwaldkreis, Hesse','ERB'),
('Erlangen-Höchstadt, Bavaria','ERH'),
('Erkelenz, North-Rhine-Westphalia','ERK'),
('Esslingen, Baden-Württemberg','ES'),
('Eisenach, Thuringia','ESA'),
('Eschenbach, Bavaria','ESB'),
('Eschwege & Werra-Meißner-Kreis, Hesse','ESW'),
('Euskirchen, North-Rhine-Westphalia','EU'),
('Eutin, Schleswig-Holstein','EUT'),
('Eberswalde, Brandenburg','EW'),
('Frankfurt am Main, Hesse','F'),
('Fallingbostel, North-Rhine-Westphalia','FAL'),
('Friedberg (Hessen) & Wetteraukreis, Hesse','FB'),
('Fulda, Hesse','FD'),
('Friedberg bei Augsburg, Bavaria','FDB'),
('Freudenstadt, Baden-Württemberg','FDS'),
('Feuchtwangen, Bavaria','FEU'),
('Frankfurt-an-der-Oder, Brandenburg','FF'),
('Fürstenfeldbruck, Bavaria','FFB'),
('Freiberg, Saxony','FG'),
('Frankfurt am Main/Höchst, Hesse','FH'),
('Finsterwalde, Brandenburg','FI'),
('Frankenberg, Hesse','FKB'),
('Flensburg, Schleswig-Holstein','FL'),
('Flöha, Saxony','FLÖ'),
('Friedrichshafen & Bodenseekreis, Baden-Württemberg','FN'),
('Forchheim, Bavaria','FO'),
('Forst, Brandenburg','FOR'),
('Freiburg im Breisgau & Breisgau-Hochschwarzwald, Baden-Württemberg','FR'),
('Freyung-Grafenau, Bavaria','FRG'),
('Friesland, Lower Saxony','FRI'),
('Bad Freienwalde, Brandenburg','FRW'),
('Freising, Bavaria','FS'),
('Frankenthal (Pfalz), Rhineland Palatinate','FT'),
('Freital, Saxony','FTL'),
('Fürth, Bavaria','FÜ'),
('Füssen, Bavaria','FÜS'),
('Fürstenwalde, Brandenburg','FW'),
('Fritzlar, Hesse','FZ'),
('Gera, Thuringia','G'),
('Gardelegen, Saxony Anhalt','GA'),
('Bad Gandersheim, Lower Saxony','GAN'),
('Garmisch-Partenkirchen, Bavaria','GAP'),
('Glauchau & Chemnitzer Land, Saxony','GC'),
('Gmünd, Baden-Württemberg','GD'),
('Gadesbusch, Mecklenburg-Vorpommern','GDB'),
('Gelsenkirchen, North-Rhine-Westphalia','GE'),
('Geldern, North-Rhine-Westphalia','GEL'),
('Gemünden, Bavaria','GEM'),
('Gerolzhofen, Bavaria','GEO'),
('Germersheim, Rhineland Palatinate','GER'),
('Gifhorn, Lower Saxony','GF'),
('Groß-Gerau, Hesse','GG'),
('Geithain, Saxony','GHA'),
('Gräfenhainichen, Saxony Anhalt','GHC'),
('Gießen, Hesse','GI'),
('Geilenkirchen, North-Rhine-Westphalia','GK'),
('Bergisch-Gladbach & Rheinisch-Bergischer Kreis, North-Rhine-Westphalia','GL'),
('Gladbeck, North-Rhine-Westphalia','GLA'),
('Gummersbach & Oberbergischer Kreis, North-Rhine-Westphalia','GM'),
('Grimmen, Mecklenburg-Vorpommern','GMN'),
('Gelnhausen, Hesse','GN'),
('Genthin, Saxony Anhalt','GNT'),
('Göttingen, Lower Saxony','GÖ'),
('St Goar, Rheinland Palatinate','GOA'),
('St Goarshausen, Rheinland Palatinate','GOH'),
('Göppingen, Baden-Württemberg','GP'),
('Görlitz, Saxony','GR'),
('Grafenau, Bavaria','GRA'),
('Grossenheim','GRH'),
('Griesbach, Bavaria','GRI'),
('Grimma, Saxony','GRM'),
('Gransee, Brandenburg','GRS'),
('Greiz, Thuringia','GRZ'),
('Goslar, Lower Saxony','GS'),
('Gütersloh, North-Rhine-Westphalia','GT'),
('Gotha, Thuringia','GTH'),
('Güstrow, Mecklenburg-Vorpommern','GÜ'),
('Guben, Brandenburg','GUB'),
('Gunzenhausen, Bavaria','GUN'),
('Gravenbroich, North-Rhine-Westphalia','GV'),
('Grevesmühlen, Mecklenburg-Vorpommern','GVM'),
('Greifswald Land, Mecklenburg-Vorpommern','GW'),
('Günzburg, Bavaria','GZ'),
('Hanover (Hannover), Lower Saxony','H'),
('Hagen, North-Rhine-Westphalia','HA'),
('Hammelburg, Bavaria','HAB'),
('Halle, Saxony-Anhalt','HAL'),
('Hamm, North-Rhine-Westphalia','HAM'),
('Haßberge, Bavaria','HAS'),
('Hansestadt Bremen','HB'),
('Hildburghausen, Thuringia','HBN'),
('Halberstadt, Saxony-Anhalt','HBS'),
('Hainichen, Saxony','HC'),
('Hechingen, Baden-Württemberg','HCH'),
('Heidelberg & Rhein-Neckar-Kreis, Baden-Württemberg','HD'),
('Heidenheim, Baden-Württemberg','HDH'),
('Haldensleben, Saxony Anhalt','HDL'),
('Helmstedt, Lower Saxony','HE'),
('Hersbruck, Bavaria','HEB'),
('Hersfeld-Rotenburg, Hesse','HEF'),
('Heide & Dithmarschen, Schleswig-Holstein','HEI'),
('Hesse State (Hesse Land) official vehicles','HEL'),
('Herne, North-Rhine-Westphalia','HER'),
('Hettstedt, Saxony Anhalt','HET'),
('Herford, North-Rhine-Westphalia','HF'),
('Bad Homburg vor der Höhe & Hochtaunuskreis, Hesse','HG'),
('Hagenow, Mecklenburg-Vorpommern','HGN'),
('Hansestadt Greifswald, Mecklenburg-Vorpommern','HGW'),
('Hansestadt Hamburg','HH'),
('Hohenmölsen, Saxony Anhalt','HHM'),
('Hildesheim, Lower Saxony','HI'),
('Heiligenstadt, Thuringia','HIG'),
('Hilpoltstein, Bavaria','HIP'),
('Heidekreis, Lower Saxony','HK'),
('Hansestadt Lübeck','HL'),
('Hamelin(Hameln)-Pyrmont, Lower Saxony','HM'),
('Hanoversch Münden, Lower Saxony','HMU'),
('Heilbronn, Baden-Württemberg','HN'),
('Hof, Bavaria','HO'),
('Hofgeismar, Hesse','HOG'),
('Hofheim, Bavaria','HOH'),
('Holzminden, Lower Saxony','HOL'),
('Homburg & Saar-Pfalz-Kreis, Saarland','HOM'),
('Horb, Baden-Württemberg','HOR'),
('Höchstadt, Bavaria','HÖS'),
('Hohenstein-Ernstthal, Saxony','HOT'),
('Heppenheim an der Bergstraße & Bergstraße, Hesse','HP'),
('Homberg & Schwalm-Eder-Kreis, Hesse','HR'),
('Hansestadt Rostock, Mecklenburg-Vorpommern','HRO'),
('Heinsberg, North-Rhine-Westphalia','HS'),
('Hochsauerlandkreis, North-Rhine-Westphalia','HSK'),
('Hansestadt Stralsund, Mecklenburg-Vorpommern','HST'),
('Hanau & Main-Kinzig-Kreis, Hesse','HU'),
('Hünfeld, Schleswig-Holstein','HÜN'),
('Husum, Schleswig-Holstein','HUS'),
('Havelberg, Saxony Anhalt','HV'),
('Havelland, Brandenburg','HVL'),
('Halle Westfalen, North-Rhine-Westphalia','HW'),
('Hansestadt Wismar, Mecklenburg-Vorpommern','HWI'),
('Höxter, North-Rhine-Westphalia','HX'),
('Hoyerswerda, Saxony','HY'),
('Herzberg, Brandenburg','HZ'),
('Stadt St Ingbert & Saar-Pfalz-Kreis, Saarland','IGB'),
('Ilm-Kreis, Thuringia','IK'),
('Ilmenau, Thuringia','IL'),
('Illertissen, Bavaria','ILL'),
('Ingolstadt, Bavaria','IN'),
('Iserlohn, North-Rhine-Westphalia','IS'),
('Itzehoe & Steinburg, Schleswig-Holstein','IZ'),
('Jena, Thuringia','J'),
('Jüterbog, Brandenburg','JB'),
('Jessen, Saxony Anhalt','JE'),
('Jever, Lower Saxony','JEV'),
('Jerichower Land, Saxony-Anhalt','JL'),
('Jülich, North-Rhine-Westphalia','JÜL'),

('Cologne (Köln), North-Rhine-Westphalia','K'),
('Karlsruhe, Baden-Württemberg','KA'),
('Karlstadt, Bavaria','KAR'),
('Korbach & Waldeck-Frankenberg, Hesse','KB'),
('Kronach, Bavaria','KC'),
('Kempten (Allgäu), Bavaria','KE'),
('Kelheim, Bavaria','KEH'),
('Kehl, Baden-Württemberg','KEL'),
('Kemnath, Bavaria','KEM'),
('Kaufbeuren, Bavaria','KF'),
('Bad Kissingen, Bavaria','KG'),
('Bad Kreuznach, Rhineland Palatinate','KH'),
('Kiel, Schleswig-Holstein','KI'),
('Kirchheimbolanden & Donnersbergkreis, Rhineland Palatinate','KIB'),
('Kempen-Krefeld, North-Rhine-Westphalia','KK'),
('Kaiserslauten, Rhineland Palatinate','KL'),
('Cleves (Kleve), North-Rhine-Westphalia','KLE'),
('Klingental, Saxony','KLT'),
('Klötze, Saxony Anhalt','KLZ'),
('Kamenz, Saxony','KM'),
('Constance (Konstanz), Baden-Württemberg','KN'),
('Koblenz, Rhineland Palatinate','KO'),
('Kötzting, Bavaria','KÖN'),
('Köthen, Saxony-Anhalt','KÖT'),
('Kotzting','KOZ'),
('Krefeld, North-Rhine-Westphalia','KR'),
('Krumbach, Bavaria','KRU'),
('Kassel, Hesse','KS'),
('Kitzingen, Bavaria','KT'),
('Kulmbach, Bavaria','KU'),
('Küzelsau & Hohenlohekreis, Baden-Württemberg','KÜN'),
('Kusel, Rhineland Palatinate','KUS'),
('Königs-Wusterhausen, Brandenburg','KW'),
('Kyritz, Brandenburg','KY'),
('Kyffhäuserkreis, Thuringia','KYF'),

('Leipzig, Saxony','L'),
('Landshut, Bavaria','LA'),
('Landau Isar, Bavaria','LAN'),
('Lauterbach, Hesse','LAT'),
('Lauf an der Pegnitz & Nürnberger Land, Bavaria','LAU'),
('Ludwigsburg, Baden-Württemberg','LB'),
('Lobenstein, Thuringia','LBS'),
('Lübz, Mecklenburg-Vorpommern','LBZ'),
('Luckau, Brandenburg','LC'),
('Landau in der Pfalz, Rhineland Palatinate','LD'),
('Lahn-Dill-Kreis, Hesse','LDK'),
('Landkreis Dahme-Spreewald, Brandenburg','LDS'),
('Lemgo, North-Rhine-Westphalia','LE'),
('Leonberg, Baden-Württemberg','LEO'),
('Leer (Ostfriesland), Lower Saxony','LER'),
('Leverkusen, North-Rhine-Westphalia','LEV'),
('Laufen, Bavaria','LF'),
('Lüneburg, Lower Saxony','LG'),
('Lüdinghausen, North-Rhine-Westphalia','LH'),
('Lindau (Bodensee), Bavaria','LI'),
('Bad Liebenwerda, Brandenburg','LIB'),
('Lichtenfels, Bavaria','LIF'),
('Lingen, Lower Saxony','LIN'),
('Lippe, North-Rhine-Westphalia','LIP'),
('Lübbecke, North-Rhine-Westphalia','LK'),
('Landsberg am Lech, Bavaria','LL'),
('Limburg-Weilburg, Hesse','LM'),
('Lübben, Brandenburg','LN'),
('Lörrach, Baden-Württemberg','LÖ'),
('Löbau, Saxony','LÖB'),
('Lohr am Main, Bavaria','LOH'),
('Landkreis Oder-Spree, Brandenburg','LOS'),
('Lippstadt, North-Rhine-Westphalia','LP'),
('Lahr, Baden-Württemberg','LR'),
('Lüdenscheid, North-Rhine-Westphalia','LS'),
('Saxony Anhalt State official vehicles','LSA'),
('Saxony State official vehicles','LSN'),
('Bad Langensalza, Thuringia','LSZ'),
('Ludwigshafen am Rhein, Rhineland Palatinate','LU'),
('Lüdenscheid, North-Rhine-Westphalia','LÜD'),
('Luckenwalde, Brandenburg','LUK'),
('Lünen, North-Rhine-Westphalia','LÜN'),
('Ludwigslust, Mecklenburg-Vorpommern','LWL'),

('Munich (München), Bavaria','M'),
('Mannheim, Baden-Württemberg','MA'),
('Marienberg, Saxony','MAB'),
('Mainburg, Bavaria','MAI'),
('Marktredwitz, Bavaria','MAK'),
('Mallersdorf, Bavaria','MAL'),
('Marktheidenfeld, Bavaria','MAR'),
('Miesbach, Bavaria','MB'),
('Malchin, Mecklenburg-Vorpommern','MC'),
('Magdeburg, Saxony-Anhalt','MD'),
('Mettmann, North-Rhine-Westphalia','ME'),
('Meldorf, Schleswig-Holstein','MED'),
('Melsungen, Hesse','MEG'),
('Meissen, Saxony','MEI'),
('Mittlerer Erzgebirgskreis, Saxony','MEK'),
('Melle, Lower Saxony','MEL'),
('Meppen, Lower Saxony','MEP'),
('Merseburg, Saxony Anhalt','MER'),
('Meschede, North-Rhine-Westphalia','MES'),
('Mellrichstadt, Bavaria','MET'),
('Mönchengladbach, North-Rhine-Westphalia','MG'),
('Bad Mergentheim, Baden-Württemberg','MGH'),
('Meiningen, Thuringia','MGN'),
('Mülheim an der Ruhr, North-Rhine-Westphalia','MH'),
('Mühlhausen','MHL'),
('Minden-Lübbecke, North-Rhine-Westphalia','MI'),
('Miltenberg, Bavaria','MIL'),
('Märkischer Kreis, North-Rhine-Westphalia','MK'),
('Main-Kinzig-Kreis, Hessen','MKK'),
('Mansfelder Land, Saxony-Anhalt','ML'),
('Memmingen, Bavaria','MM'),
('Mindelheim & Unterallgäu, Bavaria','MN'),
('Moers, North-Rhine-Westphalia','MO'),
('Marktoberdorf, Bavaria','MOD'),
('Märkisch-Oderland, Brandenburg','MOL'),
('Monschau, North-Rhine-Westphalia','MON'),
('Mosbach & Neckar-Odenwald-Kreis, Baden-Württemberg','MOS'),
('Merseburg-Querfurt, Saxony-Anhalt','MQ'),
('Marburg-Biedenkopf, Hesse','MR'),
('Münster, North-Rhine-Westphalia','MS'),
('Main-Spessart-Kreis, Bavaria','MSP'),
('Mecklenburg-Strelitz, Mecklenburg-Vorpommern','MST'),
('Montabaur, Rhineland Palatinate','MT'),
('Main-Taunus-Kreis, Hesse','MTK'),
('Muldentalkreis, Saxony','MTL'),
('Mühldorf am Inn, Bavaria','MÜ'),
('Münchberg, Bavaria','MÜB'),
('Müllheim, Baden-Württemberg','MÜL'),
('Münsingen, Baden-Württemberg','MÜN'),
('Müritz, Mecklenburg-Vorpommern','MÜR'),
('Mecklenburg-Vorpommern Land official vehicles','MVL'),
('Mittweida, Saxony','MW'),
('Mayen, Rhineland Palatinate','MY'),
('Mayen-Koblenz, Rhineland Palatinate','MYK'),
('Mainz & Mainz-Bingen, Rhineland Palatinate','MZ'),
('Merzig-Wadern, Saarland','MZG'),

('Nuremberg (Nürnberg), Bavaria','N'),
('Nabburg, Bavaria','NAB'),
('Naila, Bavaria','NAI'),
('Nauen, Brandenburg','NAU'),
('Neubrandenburg, Mecklenburg-Vorpommern','NB'),
('Neuberg an der Donau & Neuberg-Schrobenhausen, Bavaria','ND'),
('Nordhausen, Thuringia','NDH'),
('Neuss, North-Rhine-Westphalia','NE'),
('Neustadt an der Aisch & Bad Windsheim, Bavaria','NEA'),
('Nebra, Saxony Anhalt','NEB'),
('Neustadt Coburg, Bavaria','NEC'),
('Neunburg, Bavaria','NEN'),
('Bad Neustadt an der Saale & Rhön-Grabfeld, Bavaria','NES'),
('Neustadt Schwarzwald, Baden-Württemberg','NEU'),
('Neustadt an der Waldnaab, Bavaria','NEW'),
('Nordfriesland, Schleswig-Holstein','NF'),
('Neuhaus an der Rennweg, Thuringia','NH'),
('Nienberg (Weser), Lower Saxony','NI'),
('Niebüll, Schleswig-Holstein','NIB'),
('Neunkirchen/Saar, Saarland','NK'),
('Lower Saxony State official vehicles','NL'),
('Neumarkt in der Oberpfalz, Bavaria','NM'),
('Naumberg, Saxony Anhalt','NMB'),
('Neumünster, Schleswig-Holstein','NMS'),
('Nördlingen, Bavaria','NÖ'),
('Nordhorn & Grafschaft Bentheim, Lower Saxony','NOH'),
('Niederschlesischer Oberlausitzkreis, Saxony','NOL'),
('Northeim, Lower Saxony','NOM'),
('Norden, Lower Saxony','NOR'),
('Neuruppin, Brandenburg','NP'),
('Neuwied am Rhein, Rhineland Palatinate','NR'),
('Neustadt am Rübenberge, Lower Saxony','NRÜ'),
('North-Rhine-Westphalia State official vehicles','NRW'),
('Neu-Ulm, Bavaria','NU'),
('Nürtingen, Baden-Württemberg','NT'),
('Nordvorpommern, Mecklenburg-Vorpommern','NVP'),
('Neustadt an der Weinstraße, Rhineland Palatinate','NW'),
('Nordwestmecklenburg, Mecklenburg-Vorpommern','NWM'),
('Niesky, Saxony','NY'),
('Neustrelitz, Mecklenburg-Vorpommern','NZ'),

('Oberallgäu, Bavaria','OA'),
('Ostallgäu, Bavaria','OAL'),
('Oberhausen, North-Rhine-Westphalia','OB'),
('Obernburg, Bavaria','OBB'),
('Osterburg, Saxony Anhalt','OBG'),
('Oschersleben, Saxony','OC'),
('Ochsenfurt, Bavaria','OCH'),
('Bad Oldesloe & Stormarn, Schleswig-Holstein','OD'),
('Olpe, North-Rhine-Westphalia','OE'),
('Offenbach am Main, Hesse','OF'),
('Offenburg & Ortenaukreis, Baden-Württemberg','OG'),
('Ostholstein, Schleswig-Holstein','OH'),
('Osterode am Harz, Lower Saxony','OHA'),
('Öhringen, Baden-Württemberg','ÖHR'),
('Oberhavel, Brandenburg','OHV'),
('Osterholz, Lower Saxony','OHZ'),
('Ohre-Kreis, Saxony-Anhalt','OK'),
('Oldenburg, Lower Saxony','OL'),
('Oldenburg (Holstein), Schleswig-Holstein','OLD'),
('Opladen, North-Rhine-Westphalia','OP'),
('Ostprignitz-Ruppin, Brandenburg','OPR'),
('Oranienburg, Brandenburg','OR'),
('Osnabrück, Lower Saxony','OS'),
('Oberspreewald-Lausitz, Brandenburg','OSL'),
('Otterndorf, Lower Saxony','OTT'),
('Ottweiler, Saarland','OTW'),
('Oberviechtach, Bavaria','OVI'),
('Obervogtland, Saxony','OVL'),
('Ostvorpommern, Mecklenburg-Vorpommern','OVP'),
('Oschatz, Saxony','OZ'),

('Potsdam, Brandenburg','P'),
('Passau, Bavaria','PA'),
('Pfaffenhofen an der Ilm, Bavaria','PAF'),
('Pfarrkirchen & Rottal-Inn, Bavaria','PAN'),
('Parsberg, Bavaria','PAR'),
('Paderborn, North-Rhine-Westphalia','PB'),
('Parchim, Mecklenburg-Vorpommern','PCH'),
('Peine, Lower Saxony','PE'),
('Pegnitz, Bavraia','PEG'),
('Perleberg, Brandenburg','PER'),
('Pforzheim & Enzkreis, Baden-Württemberg','PF'),
('Pinneberg, Schleswig-Holstein','PI'),
('Pirna, Saxony','PIR'),
('Pritzwalk, Brandenburg','PK'),
('Plauen, Saxony','PL'),
('Plön, Schleswig-Holstein','PLÖ'),
('Potsdam-Mittelmark, Brandenburg','PM'),
('Pößneck, Thuringia','PN'),
('Prignitz, Brandenburg','PR'),
('Prüm, Rhineland Palatinate','PRÜ'),
('Pirmasens & Südwestpfalz, Rhineland Palatinate','PS'),
('Pasewalk, Mecklenburg-Vorpommern','PW'),
('Prenzlau, Brandenburg','PZ'),
('Querfurt, Saxony Anhalt','QFT'),
('Quedlinburg, Saxony-Anhalt','QLB'),
('Regensberg, Bavaria','R'),
('Ratstatt, Baden-Württemberg','RA'),
('Reichenbach, Saxony','RC'),
('Rendsburg-Eckernförde, Schleswig-Holstein','RD'),
('Ribnitz-Damgarten, Mecklenburg-Vorpommern','RDG'),
('Recklinghausen, North-Rhine-Westphalia','RE'),
('Regen, Bavaria','REG'),
('Rehau, Bavaria','REH'),
('Bad Reichenhall, Bavaria','REI'),
('Riesa-Großenhain, Saxony','RG'),
('Roth bei Nürnberg, Bavaria','RH'),
('Rinteln, Lower Saxony','RI'),
('Riedenburg, Bavaria','RID'),
('Riesa, Saxony','RIE'),
('Rochlitz, Saxony','RL'),
('Röbel/Muritz, Mecklenburg-Vorpommern','RM'),
('Rathenow, Brandenburg','RN'),
('Rosenheim, Bavaria','RO'),
('Roding, Bavaria','ROD'),
('Rotenburg bei Fulda, Hesse','ROF'),
('Rotenburg Wümme, Lower Saxony','ROH'),
('Rockenhausen, Rhineland Palatinate','ROK'),
('Rottenburg Laaber, Bavaria','ROL'),
('Rostock Land, Mecklenburg-Vorpommern','ROS'),
('Rothenburg ob der Tauber, Bavaria','ROT'),
('Rotenburg (Wümme) & Bremervörde, Lower Saxony','ROW'),
('Rhineland Palatinate State official vehicles','RPL'),
('Remscheid, North-Rhine-Westphalia','RS'),
('Roßlau, Saxony Anhalt','RSL'),
('Reutlingen, Baden-Württemberg','RT'),
('Rudolstadt','RU'),
('Rüdesheim & Rheingau-Taunus-Kreis, Hesse','RÜD'),
('Rügen, Mecklenburg-Vorpommern','RÜG'),
('Ravensburg, Baden-Württemberg','RV'),
('Rottweil, Baden-Württemberg','RW'),
('North-Rhine-Westphalia State official vehicles','RWL'),
('Rheydt, North-Rhine-Westphalia','RY'),
('Ratzeburg & Hertzogtum Lauenburg, Schleswig-Holstein','RZ'),
('Stuttgart, Baden-Württemberg','S'),
('Saarburg, Rhineland Palatinate','SAB'),
('Schwandorf, Bavaria','SAD'),
('Säckingen, Baden-Württemberg','SÄK'),
('Saarland official vehicles','SAL'),
('Stadtsteinach, Bavaria','SAN'),
('Saale-Orla Kreis','SAO'),
('Altmarkkreis Salzwedel, Saxony-Anhalt','SAW'),
('Saarbrücken, Saarland','SB'),
('Strasburg, Mecklenburg-Vorpommern','SBG'),
('Schönebeck, Saxony-Anhalt','SBK'),
('Schwabach, Bavaria','SC'),
('Schleiz, Thuringia','SCZ'),
('Sondershausen, Thuringia','SDH'),
('Stendal, Saxony-Anhalt','SDL'),
('Schwedt, Brandenburg','SDT'),
('Segeberg, Schleswig-Holstein','SE'),
('Sebnitz, Saxony','SEB'),
('Seelow, Brandenburg','SEE'),
('Scheinfeld, Bavaria','SEF'),
('Selb, Bavaria','SEL'),
('Selb, Bavaria','SF'),
('Soltau-Fallingbostel, Lower Saxony','SFA'),
('Senftenberg, Brandenburg','SFB'),
('Staßfurt, Saxony Anhalt','SFT'),
('Solingen, North-Rhine-Westphalia','SG'),
('Sangerhausen, Saxony-Anhalt','SGH'),
('Schleswig-Holstein Land official vehicles','SH'),
('Schwäbisch Hall, Baden-Württemberg','SHA'),
('Stadthagen & Schaumburg, Lower Saxony','SHG'),
('Saale-Holzland-Kreis, Thuringia','SHK'),
('Suhl, Thuringia','SHL'),
('Sangerhausen','SHS'),
('Siegen-Wittgenstein, North-Rhine-Westphalia','SI'),
('Sigmaringen, Baden-Württemberg','SIG'),
('Simmern & Rhein-Hunsrück-Kreis, Rhineland Palatinate','SIM'),
('Saalkreis, Saxony-Anhalt','SK'),
('Schleswig-Flensburg, Schleswig-Holstein','SL'),
('Schleiden (Eifel), North-Rhine-Westphalia','SLE'),
('Saalfeld-Rudolstadt, Thuringia','SLF'),
('Saulgau, Baden-Württemberg','SLG'),
('Salzlandkreis, Saxony-Anhalt','SLK'),
('Schmölin, Thuringia','SLN'),
('Saarlouis, Saarland','SLS'),
('Schlüchtern, Hesse','SLÜ'),
('Bad Salzungen, Thuringia','SLZ'),
('Schmalkalden-Meiningen, Thuringia','SM'),
('Schwabmünchen, Bavaria','SMÜ'),
('Schwerin, Mecklenburg-Vorpommern','SN'),
('Sinsheim, Baden-Württemberg','SNH'),
('Soest, North-Rhine-Westphalia','SO'),
('Schrobenhausen, Bavaria','SOB'),
('Schongau, Bavaria','SOG'),
('Saale-Orla-Kreis, Thuringia','SOK'),
('Soltau, Lower Saxony','SOL'),
('Sömmerda, Thuringia','SÖM'),
('Sonneberg, Thuringia','SON'),
('Speyer, Rhineland Palatinate','SP'),
('Spremberg, Brandenburg','SPB'),
('Spree-Neiße, Brandenburg','SPN'),
('Springe, Lower Saxony','SPR'),
('Straubing & Straubing-Bogen, Bavaria','SR'),
('Strausberg, Brandenburg','SRB'),
('Stadtroda, Thuringia','SRO'),
('Steinfurt, North-Rhine-Westphalia','ST'),
('Starnberg, Bavaria','STA'),
('Sternberg, Mecklenburg-Vorpommern','STB'),
('Stade, Lower Saxony','STD'),
('Staffelstein, Bavaria','STE'),
('Stadthagen, Lower Saxony','STH'),
('Stollberg, Saxony','STL'),
('Stockach, Baden-Württemberg','STO'),
('Siegburg & Rhein-Sieg-Kreis, North-Rhine-Westphalia','SU'),
('Sulzbach-Rosenberg, Bavaria','SUL'),
('Südliche Weinstraße, Rhineland Palatinate','SÜW'),
('Schweinfurt, Bavaria','SW'),
('Bad Schwalbach & Rheingau-Taunus-Kreis, Hesse','SWA'),
('Schwarzakreis','SWZ'),
('Syke, Lower Saxony','SY'),
('Salzgitter, Lower Saxony','SZ'),
('Schwarzenberg, Saxony','SZB'),

('Tauberbischofsheim & Main-Tauber-Kreis, Baden-Württemberg','TBB'),
('Teterow, Mecklenburg-Vorpommern','TE'),
('Teltow-Fläming, Brandenburg','TF'),
('Torgau, Saxony','TG'),
('Thurgau-Oschatz','TGO'),
('Thuringia State (Thüringen Land) official vehicles','THL'),
('German Federal Agency for Technical Relief vehicles','THW'),
('Tirschenreuth, Bavaria','TIR'),
('Torgau-Oschatz, Saxony','TO'),
('Bad Tölz-Wolfratshausen, Bavaria','TÖL'),
('Tönning, Schleswig-Holstein','TÖN'),
('Templin, Brandenburg','TP'),
('Trier, Rhineland Palatinate','TR'),
('Traunstein, Bavaria','TS'),
('Tettnang, Baden-Württemberg','TT'),
('Tübingen, Baden-Württemberg','TÜ'),
('Tuttlingen, Baden-Württemberg','TUT'),
('Überlingen, Baden-Württemberg','ÜB'),
('Uelzen, Lower Saxony','UE'),
('Ueckermünde, Mecklenburg-Vorpommern','UEM'),
('Uecker-Randow, Mecklenburg-Vorpommern','UER'),
('Uffenheim, Bavaria','UFF'),
('Unstrut-Hainich, Thuringia','UH'),
('Ulm & Alb-Donau-Kreis, Baden-Württemberg','UL'),
('Uckermark, Brandenburg','UM'),
('Unna, North-Rhine-Westphalia','UN'),
('Usingen, Hesse','USI'),
('Vogtlandkreis, Saxony','V'),
('Vaihingen, Baden-Württemberg','VAI'),
('Vogelsbergkreis, Hesse','VB'),
('Vechta, Lower Saxony','VEC'),
('Verden, Lower Saxony','VER'),
('Vilsbiburg, Bavaria','VIB'),
('Viersen, North-Rhine-Westphalia','VIE'),
('Viechtach, Bavaria','VIT'),
('Völklingen, Saarland','VK'),
('Villingen, Baden-Württemberg','VL'),
('Vilshofen, Bavaria','VOF'),
('Vohenstrauß, Bavaria','VOH'),
('Vorpommern-Rügen, Mecklenburg-Vorpommern','VR'),
('Villingen-Schwenningen & Schwarzwald-Baar-Kreis, Baden-Württemberg','VS'),
('Wuppertal, North-Rhine-Westphalia','W'),
('Waldeck, Hesse','WA'),
('Kreis Warendorf, North-Rhine-Westphalia','WAF'),
('Wartburgkreis, Thuringia','WAK'),
('Westliche Altmark','WAM'),
('Wanne-Eickel, North-Rhine-Westphalia','WAN'),
('Warburg, North-Rhine-Westphalia','WAR'),
('Wattenscheid, North-Rhine-Westphalia','WAT'),
('Wittenberg, Saxony-Anhalt','WB'),
('Worbis, Thuringia','WBS'),
('Weidenbrück, North-Rhine-Westphalia','WD'),
('Werdau, Saxony','WDA'),
('Weimar, Thuringia','WE'),
('Westerburg, Rhineland Palatinate','WEB'),
('Wegscheid, Bavaria','WEG'),
('Weimarer Land (Kreis Apolda)','WEI'),
('Weilburg, Hesse','WEL'),
('Wesermünde, Lower Saxony','WEM'),
('Weiden in der Oberpfalz, Bavaria','WEN'),
('Wertingen, Bavaria','WER'),
('Wesel, North-Rhine-Westphalia','WES'),
('Wolfenbüttel, Lower Saxony','WF'),
('Wangen, Baden-Württemberg','WG'),
('Wilhelmshaven, Lower Saxony','WHV'),
('Wiesbaden, Hesse','WI'),
('Wittlich & Bernkastel-Wittlich, Rhineland Palatinate','WIL'),
('Wismarer Land','WIS'),
('Witten, North-Rhine-Westphalia','WIT'),
('Witzenhausen, Hesse','WIZ'),
('Wittstock, Brandenburg','WK'),
('Winsen (Luhe) & Harburg, Lower Saxony','WL'),
('Wolgast, Mecklenburg-Vorpommern','WLG'),
('Weilheim-Schongau, Bavaria','WM'),
('Wolmirstedt, Saxony Anhalt','WMS'),
('Waiblingen & Rems-Murr-Kreis, Baden-Württemberg','WN'),
('St Wendel, Saarland','WND'),
('Worms, Rhineland Palatinate','WO'),
('Wolfsburg, Lower Saxony','WOB'),
('Wolfhagen, Hesse','WOH'),
('Wolfach, Baden-Württemberg','WOL'),
('Wolfratshausen, Bavaria','WOR'),
('Wolfstein, Bavaria','WOS'),
('Wernigerode, Saxony-Anhalt','WR'),
('Waren, Mecklenburg-Vorpommern','WRN'),
('Wasserburg, Bavaria','WS'),
('Weißenfels, Saxony-Anhalt','WSF'),
('Westerstede & Ammerland, Lower Saxony','WST'),
('Weißwasser, Saxony','WSW'),
('Waldshut, Baden-Württemberg','WT'),
('Wittlage, Lower Saxony','WTL'),
('Wittmund, Lower Saxony','WTM'),
('Würzburg, Bavaria','WÜ'),
('Weißenburg-Gunzenhausen, Bavaria','WUG'),
('Waldmünchen, Bavaria','WUM'),
('Wunsiedel am Fichtelgebirge, Bavaria','WUN'),
('Wurzen, Saxony','WUR'),
('Westerwaldkreis, Rhineland Palatinate','WW'),
('Wetzlar, Hesse','WZ'),
('Wanzleben, Saxony Anhalt','WZL'),
('NATO Forces vehicles','X'),
('Armed Forces vehicles','Y'),
('Zwickauer Land, Saxony','Z'),
('Zerbst, Saxony-Anhalt','ZE'),
('Zell, Rhineland Palatinate','ZEL'),
('Löbau-Zittau','ZI'),
('Ziegenhain, Hesse','ZIG'),
('Zschopau, Saxony','ZP'),
('Zeulenroda, Thuringia','ZR'),
('Zossen, Brandenburg','ZS'),
('Zweibrücken, Rhineland Palatinate','ZW'),
('Zeitz, Saxony Anhalt','ZZ');
UNLOCK TABLES;

ALTER TABLE germany_entity ADD INDEX germany_index (description, region);