DROP TABLE IF EXISTS `greece_entity`;

CREATE TABLE `greece_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `greece_entity` WRITE;
/*!40000 ALTER TABLE `greece_entity` DISABLE KEYS */;
INSERT INTO `greece_entity` VALUES
(1,'Achaia prefecture - Patras','AA'),
(2,'Kavala prefecture - Kavala {motorcycles}','AB'),
(3,'Lasithi prefecture - Agios Nikolaos','AE'),
(4,'Achaia prefecture - Patras','AZ'),
(5,'Xanthi prefecture - Xanthi','AH'),
(6,'Xanthi prefecture - Xanthi','AHH'),
(7,'Aitoloakarnania prefecture - Agrinio area.','AI'),
(8,'Aitoloakarnania prefecture - Agrinio area.','AII'),
(9,'Laconia prefecture - Sparti','AK'),
(10,'Phokida prefecture - Amfissa','AM'),
(11,'Lasithi prefecture - Agios Nikolaos','AN'),
(12,'Achaia prefecture - Patras {motorcycles}','AO'),
(13,'Argolis (Argolida) prefecture - Nafplio','AP'),
(14,'Arta prefecture - Arta','AT'),
(15,'Achaia prefecture - Patras {motorcycles}','AY'),
(16,'Achaia prefecture - Patras','AX'),
(17,'Magnesia prefecture - Volos {motorcycles}','BA'),
(18,'Magnesia prefecture - Volos {motorcycles}','BB'),
(19,'Piraeus prefecture {motorcycles}','BE'),
(20,'Piraeus prefecture {motorcycles}','BZ'),
(21,'Piraeus prefecture {motorcycles}','BH'),
(22,'Boeotia (Viotia) prefecture - Livadeia','BI'),
(23,'East Attica prefecture - Pallini','BK'),
(24,'East Attica prefecture - Pallini','BM'),
(25,'West Attica prefecture - Elefsina','BN'),
(26,'Magnesia prefecture - Volos ','BO'),
(27,'Pella Prefecture','BOP'),
(28,'West Attica prefecture - Elefsina','BP'),
(29,'Magnesia prefecture - Volos','BT'),
(30,'Boeotia (Viotia) prefecture - Livadeia','BY'),
(31,'Piraeus prefecture {motorcycles}','BX'),
(32,'Dodecanese prefecture - Kos island {motorcycles}','EA'),
(33,'Evros prefecture - Alexandroupoli','EB'),
(34,'Evros prefecture - Alexandroupoli','EBB'),
(35,'Pella Prefecture - Edessa','EE'),
(36,'Pella Prefecture - Edessa','EEE'),
(37,'Cyclades prefecture - Ermoupoli {motorcycles}','EZ'),
(38,'Euboea (Evia) prefecture - Chalkida {motorcycles}','EH'),
(39,'Euboea (Evia) prefecture - Chalkida {motorcycles}','EI'),
(40,'Cyclades prefecture - Ermoupoli','EM'),
(41,'Serres prefecture - Serres','EP'),
(42,'Corfu (Kerkyra) prefecture - Corfu {motorcycles}','ET'),
(43,'Lefkada prefecture - Lefkada ','EY'),
(44,'Rodos Island','EYA'),
(45,'tax free cars of offshore companies','EYY'),
(46,'Kilkis prefecture - Kilkis','EX'),
(47,'Zakynthos prefecture - Zakynthos','ZA'),
(48,'Zakynthos prefecture - Zakynthos','ZB'),
(49,'Thessaloniki prefecture','ZE'),
(50,'Athens prefecture','ZZ'),
(51,'Athens prefecture','ZH'),
(52,'Thessaloniki prefecture','ZI'),
(53,'Athens prefecture','ZK'),
(54,'Athens prefecture','ZM'),
(55,'Piraeus prefecture','ZN'),
(56,'Thessaloniki prefecture','ZO'),
(57,'Piraeus prefecture {motorcycles}','ZP'),
(58,'West Attica prefecture - Elefsina {motorcycles}','ZT'),
(59,'East Attica prefecture - Pallini','ZY'),
(60,'East Attica prefecture - Pallini','ZX'),
(61,'Ilia prefecture - Pyrgos','HA'),
(62,'Athens prefecture {motorcycles}','HB'),
(63,'Ilia prefecture - Pyrgos {motorcycles}','HE'),
(64,'Heraklion prefecture - Heraklion','HZ'),
(65,'Heraklion prefecture - Heraklion {motorcycles}','HH'),
(66,'Heraklion prefecture - Heraklion {motorcycles}','HI'),
(67,'Heraklion prefecture - Heraklion ','HK'),
(68,'Chania Prefecture','HKH'),
(69,'Chania Prefecture','HKZ'),
(70,'Imathia prefecture - Veria','HM'),
(71,'Thesprotia prefecture - Igoumenitsa','HN'),
(72,'Xanthi prefecture - Xanthi {motorcycles}','HO'),
(73,'Heraklion prefecture - Heraklion','HP'),
(74,'Xanthi prefecture - Xanthi','HT'),
(75,'Phthiotis (Fthiotida) prefecture - Lamia','HY'),
(76,'Imathia prefecture - Veria','HX'),
(77,'Athens prefecture','IB'),
(78,'Athens prefecture','IE'),
(79,'Athens prefecture','IZ'),
(80,'Athens prefecture','IH'),
(81,'Euboea Prefecture','IHA'),
(82,'Ioannina prefecture - Ioannina','II'),
(83,'Athens prefecture','IK'),
(84,'Athens prefecture','IM'),
(85,'Ioannina prefecture - Ioannina','IN'),
(86,'Athens prefecture','IO'),
(87,'Athens prefecture','IP'),
(88,'Athens prefecture','IT'),
(89,'Athens prefecture','IY'),
(90,'Serres prefecture','IX'),
(91,'Karditsa prefecture - Karditsa','KA'),
(92,'Karditsa prefecture - Karditsa','KAA'),
(93,'Kavala prefecture - Kavala ','KB'),
(94,'Kavala prefecture - Kavala ','KBB'),
(95,'Kefalonia and Ithaca prefecture - Argostoli','KE'),
(96,'Kefalonia and Ithaca prefecture - Argostoli','KEE'),
(97,'Kozani prefecture - Kozani','KZ'),
(98,'Kozani prefecture - Kozani','KZZ'),
(99,'Evrytania prefecture - Karpenisi','KH'),
(100,'Kilkis prefecture - Kilkis','KI'),
(101,'Messinia prefecture - Kalamata','KM'),
(102,'Pieria prefecture - Katerini','KN'),
(103,'Pieria prefecture - Katerini','KNZ'),
(104,'Rhodope (Rodopi) prefecture - Komotini','KO'),
(105,'Thessaloniki prefecture','KOH'),
(106,'Thessaloniki prefecture','KOK'),
(107,'Heraklio prefecture {motorcycles}','KOP'),
(108,'Corinthia prefecture - Corinth (Korinthos)','KP'),
(109,'Kastoria prefecture - Kastoria','KT'),
(110,'Corfu (Kerkyra) prefecture - Corfu','KY'),
(111,'Dodecanese prefecture - Kos island','KX'),
(112,'Rodos Island','KXA'),
(113,'Chalkidiki prefecture - Polygyros','MA'),
(114,'Samos prefecture - Samos','MB'),
(115,'Aitoloakarnania prefecture - Messolongi','ME'),
(116,'Messinia prefecture - Kalamata {motorcycles}','MZ'),
(117,'Lesvos prefecture - Myrina (Limnos island)','MH'),
(118,'Phthiotis (Fthiotida) prefecture - Lamia','MI'),
(119,'Karditsa prefecture - Karditsa','MK'),
(120,'Pella Prefecture - Edessa','MM'),
(121,'Kozani prefecture - Kozani','MN'),
(122,'Samos prefecture - Samos','MO'),
(123,'Rodos Island {motorcycles}','MOK'),
(124,'Rodos Island {motorcycles}','MOM'),
(125,'Rodos Island {motorcycles}','MOP'),
(126,'Laconia prefecture - Sparti','MP'),
(127,'Lesbos prefecture - Mytilini {motorcycles}','MT'),
(128,'Lesbos (Lesvos) prefecture - Mytilini ','MY'),
(129,'Rodos Island','MYZ'),
(130,'Evros prefecture - Alexandroupoli','MX'),
(131,'Thessaloniki prefecture - Thessaloniki','NA'),
(132,'Thessaloniki prefecture - Thessaloniki','NB'),
(133,'Thessaloniki prefecture - Thessaloniki','NE'),
(134,'Thessaloniki prefecture - Thessaloniki','NZ'),
(135,'Thessaloniki prefecture - Thessaloniki','NH'),
(136,'Thessaloniki prefecture - Thessaloniki','NI'),
(137,'Thessaloniki prefecture - Thessaloniki','NK'),
(138,'Thessaloniki prefecture - Thessaloniki {motorcycles}','NM'),
(139,'Thessaloniki prefecture - Thessaloniki {motorcycles}','NN'),
(140,'Thessaloniki prefecture - Thessaloniki {motorcycles}','NO'),
(141,'Thessaloniki prefecture {motorcycles}','NP'),
(142,'Thessaloniki prefecture','NT'),
(143,'Thessaloniki prefecture','NY'),
(144,'Thessaloniki prefecture','NX'),
(145,'Athens {motorcycles}','OA'),
(146,'Athens {motorcycles}','OB'),
(147,'Athens {motorcycles}','OE'),
(148,'Athens {motorcycles}','OZ'),
(149,'Athens {motorcycles}','OH'),
(150,'Athens {motorcycles}','OI'),
(151,'Athens {motorcycles}','OK'),
(152,'Athens {motorcycles}','OM'),
(153,'Athens {motorcycles}','ON'),
(154,'Athens {motorcycles}','OO'),
(155,'Evros prefecture - Orestiada area','OP'),
(156,'Athens','OT'),
(157,'Athens {motorcycles}','OY'),
(158,'Athens ','OX'),
(159,'Florina prefecture - Florina','PA'),
(160,'Florina prefecture - Florina','PAA'),
(161,'Corinthia prefecture - Corinth','PB'),
(162,'Rethymno prefecture - Rethymno ','PE'),
(163,'Rethymno prefecture - Rethymno ','PEE'),
(164,'Preveza prefecture - Preveza ','PZ'),
(165,'Preveza prefecture - Preveza ','PZB'),
(166,'Rethymno prefecture - Rethymno {motorcycles}','PH'),
(167,'Larissa prefecture - Larissa','PI'),
(168,'Dodecanese prefecture - Rodos (Rhodes)','PK'),
(169,'Drama prefecture - Drama','PM'),
(170,'Drama prefecture - Drama','PMZ'),
(171,'Grevena prefecture - Grevena','PN'),
(172,'Dodecanese prefecture - Rhodes (Rodos)','PO'),
(173,'Larissa prefecture - Larissa','PP'),
(174,'Larissa prefecture - Larissa','PT'),
(175,'Dodecanese prefecture - Rodos (Rhodes) {motorcycles}','PY'),
(176,'Dodecanese prefecture - Rodos (Rhodes)','PX'),
(177,'Corfu (Kerkyra) prefecture - Corfu {motorcycles}','TB'),
(178,'Corfu (Kerkyra) prefecture - Corfu','TE'),
(179,'Piraeus prefecture {motorcycles}','TZ'),
(180,'Aitoloakarnania prefecture - Agrinio area','TH'),
(181,'Pieria prefecture - Katerini','TI'),
(182,'Trikala prefecture - Trikala','TK'),
(183,'Argolis (Argolida) prefecture - Nafplio','TM'),
(184,'Trikala prefecture - Trikala','TN'),
(185,'Drama prefecture - Drama','TO'),
(186,'Arcadia prefecture - Tripoli','TP'),
(187,'Rhodope prefecture','TT'),
(188,'Chania prefecture - Chania {motorcycles}','TY'),
(189,'Preveza prefecture - Preveza','TX'),
(190,'Athens prefecture','YA'),
(191,'Athens prefecture','YB'),
(192,'Athens prefecture','YE'),
(193,'Athens prefecture','YZ'),
(194,'Athens prefecture','YH'),
(195,'Euboea Prefecture','YHA'),
(196,'Piraeus prefecture','YI'),
(197,'Piraeus prefecture','YK'),
(198,'Piraeus prefecture','YM'),
(199,'Piraeus prefecture','YN'),
(200,'West Attica prefecture - Elefsina','YO'),
(201,'West Attica prefecture - Elefsina','YP'),
(202,'West Attica prefecture - Elefsina','YT'),
(203,'East Attica prefecture - Pallini','YY'),
(204,'East Attica prefecture - Pallini','YX'),
(205,'Euboea (Evia) prefecture - Chalkida','XA'),
(206,'Chania prefecture - Chania {motorcycles}','XB'),
(207,'Athens prefecture {now used for both motorcycles and cars}','XE'),
(208,'Athens prefecture {motorcycles}','XZ'),
(209,'Athens prefecture {motorcycles}','XH'),
(210,'Chios prefecture - Chios','XI'),
(211,'Chalkidiki prefecture - Polygyros','XK'),
(212,'Athens prefecture','XM'),
(213,'Chania prefecture - Chania ','XN'),
(214,'Chania prefecture - Chania {motorcycles} ','XNO'),
(215,'Chios prefecture - Chios {motorcycles}','XO'),
(216,'Athens prefecture {motorcycles}','XP'),
(217,'Athens prefecture {motorcycles}','XT'),
(218,'Athens prefecture {motorcycles}','XY'),
(219,'Athens prefecture {motorcycles}','XX'),
(220,'Athens International Airport service vehicles','AIA');
UNLOCK TABLES;