DROP TABLE IF EXISTS `italian_entity`;

CREATE TABLE `italian_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `italian_entity` WRITE;
/*!40000 ALTER TABLE `italian_entity` DISABLE KEYS */;
INSERT INTO `italian_entity` VALUES
(1,'Agrigento','AG'),
(2,'Alessandria','AL'),
(3,'Ancona','AN'),
(4,'Aosta / Aoste','AO'),
(5,'Ascoli Piceno','AP'),
(6,'L\'Aquila','AQ'),
(7,'Arezzo','AR'),
(8,'Asti','AT'),
(9,'Avellino','AV'),
(10,'Bari','BA'),
(11,'Bergamo','BG'),
(12,'Biella','BI'),
(13,'Belluno','BL'),
(14,'Benevento','BN'),
(15,'Bologna','BO'),
(16,'Brindisi','BR'),
(17,'Brescia','BS'),
(18,'Barletta-Andria-Trani','BT'),
(19,'Bolzano / Bozen','BZ'),
(20,'Cagliari','CA'),
(21,'Campobasso','CB'),
(22,'Caserta','CE'),
(23,'Chieti','CH'),
(24,'Caltanissetta','CL'),
(25,'Cuneo','CN'),
(26,'Como','CO'),
(27,'Cremona','CR'),
(28,'Cosenza','CS'),
(29,'Catania','CT'),
(30,'Catanzaro','CZ'),
(31,'Enna','EN'),
(32,'Forlì-Cesena','FC'),
(33,'Ferrara','FE'),
(34,'Foggia','FG'),
(35,'Florence (Firenze)','FI'),
(36,'Fermo','FM'),
(37,'Frosinone','FR'),
(38,'Genoa (Genova)','GE'),
(39,'Gorizia','GO'),
(40,'Grosseto','GR'),
(41,'Imperia','IM'),
(42,'Isernia','IS'),
(43,'Crotone','KR'),
(44,'Lecco','LC'),
(45,'Lecce','LE'),
(46,'Leghorn (Livorno)','LI'),
(47,'Lodi','LO'),
(48,'Latina','LT'),
(49,'Lucca','LU'),
(50,'Monza and Brianza','MB'),
(51,'Macerata','MC'),
(52,'Messina','ME'),
(53,'Milan (Milano)','MI'),
(54,'Mantua (Mantova)','MN'),
(55,'Modena','MO'),
(56,'Massa-Carrara','MS'),
(57,'Matera','MT'),
(58,'Naples (Napoli)','NA'),
(59,'Novara','NO'),
(60,'Nuoro','NU'),
(61,'Oristano','OR'),
(62,'Palermo','PA'),
(63,'Piacenza','PC'),
(64,'Padua (Padova)','PD'),
(65,'Pescara','PE'),
(66,'Perugia','PG'),
(67,'Pisa','PI'),
(68,'Pordenone','PN'),
(69,'Prato','PO'),
(70,'Parma','PR'),
(71,'Pistoia','PT'),
(72,'Pesaro-Urbino','PU'),
(73,'Pavia','PV'),
(74,'Potenza','PZ'),
(75,'Ravenna','RA'),
(76,'Reggio Calabria','RC'),
(77,'Reggio Emilia','RE'),
(78,'Ragusa','RG'),
(79,'Rieti','RI'),
(80,'Rimini','RN'),
(81,'Rovigo','RO'),
(82,'Rome (Roma)','Roma'),
(83,'Salerno','SA'),
(84,'Siena','SI'),
(85,'Sondrio','SO'),
(86,'La Spezia','SP'),
(87,'Syracuse (Siracusa)','SR'),
(88,'Sassari','SS'),
(89,'South Sardinia','SU'),
(90,'Savona','SV'),
(91,'Taranto','TA'),
(92,'Teramo','TE'),
(93,'Trent (Trento)','TN'),
(94,'Turin (Torino)','TO'),
(95,'Trapani','TP'),
(96,'Terni','TR'),
(97,'Trieste','TS'),
(98,'Treviso','TV'),
(99,'Udine','UD'),
(100,'Varese','VA'),
(101,'Verbania','VB'),
(102,'Vercelli','VC'),
(103,'Venice (Venezia)','VE'),
(104,'Vicenza','VI'),
(105,'Verona','VR'),
(106,'Viterbo','VT'),
(107,'Vibo Valentia','VV');
UNLOCK TABLES;

ALTER TABLE italian_entity ADD INDEX italian_index (description, region);