DROP TABLE IF EXISTS `norway_entity`;
CREATE TABLE `norway_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `norway_entity` WRITE;
/*!40000 ALTER TABLE `armenia_entity` DISABLE KEYS */;
INSERT INTO `norway_entity` (description, region) VALUES
('Asker and Bærum, Viken','BL'),
('Asker and Bærum, Viken','BN'),
('Asker and Bærum, Viken','BP'),
('Asker and Bærum, Viken','BR'),
('Asker and Bærum, Viken','BS'),
('Asker and Bærum, Viken','BT'),
('Asker and Bærum, Viken','BU'),
('Asker and Bærum, Viken','BV'),
('Asker and Bærum, Viken','BX'),
('Asker and Bærum, Viken','BY'),
('Asker and Bærum, Viken','BZ'),
('Asker and Bærum, Viken','CA'),
('Asker and Bærum, Viken','CB'),
('Drammen, Viken','KE'),
('Drammen, Viken','KF'),
('Drammen, Viken','KH'),
('Drammen, Viken','KJ'),
('Drammen, Viken','KK'),
('Drammen, Viken','KL'),
('Drammen, Viken','KN'),
('Drammen, Viken','KN'),
('Drammen, Viken','KP'),
('Drammen, Viken','KR'),
('Drammen, Viken','KS'),
('Drøbak, Viken','BC'),
('Drøbak, Viken','BD'),
('Drøbak, Viken','BE'),
('Drøbak, Viken','BF'),
('Drøbak, Viken','BH'),
('Drøbak, Viken','BJ'),
('Drøbak, Viken','BK'),
('Gol, Viken','KB'),
('Gol, Viken','KC'),
('Gol, Viken','KD'),
('Hafslund, Viken','AD'),
('Hafslund, Viken','AR'),
('Hafslund, Viken','AS'),
('Hafslund, Viken','AT'),
('Hafslund, Viken','AU'),
('Hafslund, Viken','AV'),
('Hafslund, Viken','AW'),
('Hafslund, Viken','DW'),
('Hafslund, Viken','FL'),
('Hafslund, Viken','ES'),
('Halden, Viken','AA'),
('Halden, Viken','AB'),
('Halden, Viken','AC'),
('Hønefoss, Viken','JU'),
('Hønefoss, Viken','JV'),
('Hønefoss, Viken','JX'),
('Hønefoss, Viken','JY'),
('Hønefoss, Viken','JZ'),
('Hønefoss, Viken','KA'),
('Jessheim, Viken','CV'),
('Jessheim, Viken','CX'),
('Jessheim, Viken','CY'),
('Jessheim, Viken','CZ'),
('Jessheim, Viken','CU'),
('Kongsberg, Viken','KT'),
('Kongsberg, Viken','KU'),
('Kongsberg, Viken','KV'),
('Kongsberg, Viken','KX'),
('Kongsberg, Viken','KY'),
('Lillestrøm, Viken','CC'),
('Lillestrøm, Viken','CE'),
('Lillestrøm, Viken','CF'),
('Lillestrøm, Viken','CH'),
('Lillestrøm, Viken','CJ'),
('Lillestrøm, Viken','CK'),
('Lillestrøm, Viken','CL'),
('Lillestrøm, Viken','CN'),
('Lillestrøm, Viken','CP'),
('Lillestrøm, Viken','CR'),
('Lillestrøm, Viken','CS'),
('Lillestrøm, Viken','CT'),
('Lillestrøm, Viken','CU'),
('Moss, Viken','AX'),
('Moss, Viken','AY'),
('Moss, Viken','AZ'),
('Moss, Viken','BA'),
('Mysen, Viken','AJ'),
('Mysen, Viken','AK'),
('Mysen, Viken','AL'),
('Mysen, Viken','AN'),
('Mysen, Viken','AP'),
('Mysen, Viken','FN'),
('Mysen, Viken','BW'),
('Sarpsborg, Viken','AE'),
('Sarpsborg, Viken','AF'),
('Sarpsborg, Viken','AH'),
('Oslo, Oslo','DA'),
('Oslo, Oslo','DB'),
('Oslo, Oslo','DC'),
('Oslo, Oslo','DD'),
('Oslo, Oslo','DE'),
('Oslo, Oslo','DF'),
('Oslo, Oslo','DH'),
('Oslo, Oslo','DJ'),
('Oslo, Oslo','DK'),
('Oslo, Oslo','DL'),
('Oslo, Oslo','DN'),
('Oslo, Oslo','DP'),
('Oslo, Oslo','DR'),
('Oslo, Oslo','DS'),
('Oslo, Oslo','DT'),
('Oslo, Oslo','DU'),
('Oslo, Oslo','DV'),
('Oslo, Oslo','DX'),
('Oslo, Oslo','DY'),
('Oslo, Oslo','DZ'),
('Oslo, Oslo','EA'),
('Oslo, Oslo','EF'),
('Oslo, Oslo','EH'),
('Oslo, Oslo','EJ'),
('Oslo, Oslo','EN'),
('Oslo, Oslo','EP'),
('Oslo, Oslo','ER'),
('Oslo, Oslo','EU'),
('Elverum, Innlandet','HB'),
('Elverum, Innlandet','HC'),
('Elverum, Innlandet','HD'),
('Elverum, Innlandet','HE'),
('Elverum, Innlandet','HA'),
('Elverum, Innlandet','FZ'),
('Fagernes, Innlandet','JR'),
('Fagernes, Innlandet','JS'),
('Fagernes, Innlandet','JT'),
('Gjøvik, Innlandet','JC'),
('Gjøvik, Innlandet','JD'),
('Gjøvik, Innlandet','JE'),
('Gjøvik, Innlandet','JF'),
('Gjøvik, Innlandet','JH'),
('Gjøvik, Innlandet','JJ'),
('Gjøvik, Innlandet','JK'),
('Gjøvik, Innlandet','JL'),
('Gjøvik, Innlandet','JN'),
('Gjøvik, Innlandet','JP'),
('Hamar, Innlandet','FS'),
('Hamar, Innlandet','FT'),
('Hamar, Innlandet','FU'),
('Hamar, Innlandet','FV'),
('Hamar, Innlandet','FX'),
('Hamar, Innlandet','FY'),
('Hamar, Innlandet','FZ'),
('Hamar, Innlandet','FW'),
('Hamar, Innlandet','ET'),
('Kongsvinger, Innlandet','HJ'),
('Kongsvinger, Innlandet','HK'),
('Kongsvinger, Innlandet','HL'),
('Kongsvinger, Innlandet','HN'),
('Kongsvinger, Innlandet','HP'),
('Kongsvinger, Innlandet','HR'),
('Lillehammer, Innlandet','HS'),
('Lillehammer, Innlandet','HT'),
('Lillehammer, Innlandet','HU'),
('Lillehammer, Innlandet','HV'),
('Lillehammer, Innlandet','HX'),
('Lillehammer, Innlandet','FB'),
('Otta, Innlandet','HZ'),
('Otta, Innlandet','JA'),
('Otta, Innlandet','JB'),
('Tynset, Innlandet','HF'),
('Tynset, Innlandet','HH'),
('Horten, Vestfold og Telemark','KZ'),
('Horten, Vestfold og Telemark','LA'),
('Horten, Vestfold og Telemark','LB'),
('Horten, Vestfold og Telemark','LC'),
('Horten, Vestfold og Telemark','LD'),
('Larvik, Vestfold og Telemark','LS'),
('Larvik, Vestfold og Telemark','LT'),
('Larvik, Vestfold og Telemark','LU'),
('Larvik, Vestfold og Telemark','LV'),
('Larvik, Vestfold og Telemark','LX'),
('Larvik, Vestfold og Telemark','LZ'),
('Larvik, Vestfold og Telemark','NA'),
('Larvik, Vestfold og Telemark','NB'),
('Larvik, Vestfold og Telemark','NC'),
('Notodden, Vestfold og Telemark','NV'),
('Notodden, Vestfold og Telemark','NX'),
('Notodden, Vestfold og Telemark','NY'),
('Notodden, Vestfold og Telemark','NZ'),
('Rjukan, Vestfold og Telemark','PA'),
('Rjukan, Vestfold og Telemark','PB'),
('Sandefjord, Vestfold og Telemark','LY'),
('Sandefjord, Vestfold og Telemark','NA'),
('Skien, Vestfold og Telemark','ND'),
('Skien, Vestfold og Telemark','NE'),
('Skien, Vestfold og Telemark','NF'),
('Skien, Vestfold og Telemark','NH'),
('Skien, Vestfold og Telemark','NJ'),
('Skien, Vestfold og Telemark','NK'),
('Skien, Vestfold og Telemark','NL'),
('Skien, Vestfold og Telemark','NN'),
('Skien, Vestfold og Telemark','NP'),
('Skien, Vestfold og Telemark','NR'),
('Skien, Vestfold og Telemark','NT'),
('Skien, Vestfold og Telemark','NU'),
('Tønsberg, Vestfold og Telemark','LH'),
('Tønsberg, Vestfold og Telemark','LJ'),
('Tønsberg, Vestfold og Telemark','LK'),
('Tønsberg, Vestfold og Telemark','LL'),
('Tønsberg, Vestfold og Telemark','LN'),
('Tønsberg, Vestfold og Telemark','LP'),
('Tønsberg, Vestfold og Telemark','LR'),
('Tønsberg, Vestfold og Telemark','LD'),
('Arendal, Agder','PC'),
('Arendal, Agder','PD'),
('Arendal, Agder','PE'),
('Arendal, Agder','PF'),
('Arendal, Agder','PH'),
('Arendal, Agder','PJ'),
('Arendal, Agder','PK'),
('Flekkefjord, Agder','RA'),
('Flekkefjord, Agder','RB'),
('Kristiansand, Agder','PN'),
('Kristiansand, Agder','PP'),
('Kristiansand, Agder','PR'),
('Kristiansand, Agder','PS'),
('Kristiansand, Agder','PT'),
('Kristiansand, Agder','PU'),
('Kristiansand, Agder','PV'),
('Kristiansand, Agder','PW'),
('Mandal, Agder','PX'),
('Mandal, Agder','PY'),
('Mandal, Agder','PZ'),
('Mandal, Agder','RC'),
('Mandal, Agder','RD'),
('Setesdal, Agder','PL'),
('Setesdal, Agder','LF'),
('Egersund, Rogaland','RZ'),
('Egersund, Rogaland','SA'),
('Egersund, Rogaland','SB'),
('Haugesund, Rogaland','SC'),
('Haugesund, Rogaland','SD'),
('Haugesund, Rogaland','SE'),
('Haugesund, Rogaland','SF'),
('Haugesund, Rogaland','SH'),
('Haugesund, Rogaland','SJ'),
('Haugesund, Rogaland','SK'),
('Haugesund, Rogaland','SL'),
('Stavanger, Rogaland','RE'),
('Stavanger, Rogaland','RF'),
('Stavanger, Rogaland','RH'),
('Stavanger, Rogaland','RJ'),
('Stavanger, Rogaland','RK'),
('Stavanger, Rogaland','RL'),
('Stavanger, Rogaland','RN'),
('Stavanger, Rogaland','RP'),
('Stavanger, Rogaland','RR'),
('Stavanger, Rogaland','RS'),
('Stavanger, Rogaland','RT'),
('Stavanger, Rogaland','RU'),
('Stavanger, Rogaland','RV'),
('Stavanger, Rogaland','RX'),
('Stavanger, Rogaland','RY'),
('Stavanger, Rogaland','RW'),
('Bergen, Vestland','SN'),
('Bergen, Vestland','SP'),
('Bergen, Vestland','SR'),
('Bergen, Vestland','SS'),
('Bergen, Vestland','ST'),
('Bergen, Vestland','SU'),
('Bergen, Vestland','SV'),
('Bergen, Vestland','SX'),
('Bergen, Vestland','SY'),
('Bergen, Vestland','SZ'),
('Bergen, Vestland','TA'),
('Bergen, Vestland','TB'),
('Bergen, Vestland','TC'),
('Bergen, Vestland','TD'),
('Bergen, Vestland','TE'),
('Bergen, Vestland','HW'),
('Førde, Vestland','TV'),
('Førde, Vestland','TX'),
('Førde, Vestland','TY'),
('Førde, Vestland','TZ'),
('Nordfjordeid, Vestland','UA'),
('Nordfjordeid, Vestland','UB'),
('Odda, Vestland','TS'),
('Odda, Vestland','TT'),
('Odda, Vestland','TU'),
('Sogndal, Vestland','UC'),
('Sogndal, Vestland','UD'),
('Stord, Vestland','TL'),
('Stord, Vestland','TN'),
('Stord, Vestland','TP'),
('Stord, Vestland','TR'),
('Voss, Vestland','TF'),
('Voss, Vestland','TH'),
('Voss, Vestland','TJ'),
('Voss, Vestland','TK'),
('Kristiansund, Møre og Romsdal','UX'),
('Kristiansund, Møre og Romsdal','UY'),
('Kristiansund, Møre og Romsdal','UZ'),
('Kristiansund, Møre og Romsdal','VA'),
('Molde, Møre og Romsdal','UR'),
('Molde, Møre og Romsdal','US'),
('Molde, Møre og Romsdal','UT'),
('Molde, Møre og Romsdal','UU'),
('Molde, Møre og Romsdal','UV'),
('Sunndalsøra, Møre og Romsdal','VB'),
('Sunndalsøra, Møre og Romsdal','VC'),
('Ørsta, Møre og Romsdal','UN'),
('Ørsta, Møre og Romsdal','UP'),
('Ørsta, Møre og Romsdal','BB'),
('Ålesund, Møre og Romsdal','UE'),
('Ålesund, Møre og Romsdal','UF'),
('Ålesund, Møre og Romsdal','UH'),
('Ålesund, Møre og Romsdal','UJ'),
('Ålesund, Møre og Romsdal','UK'),
('Ålesund, Møre og Romsdal','UL'),
('Brekstad, Trøndelag','XA'),
('Brekstad, Trøndelag','XB'),
('Brekstad, Trøndelag','XC'),
('Levanger, Trøndelag','XK'),
('Levanger, Trøndelag','XL'),
('Levanger, Trøndelag','VW'),
('Namsos, Trøndelag','XR'),
('Namsos, Trøndelag','XS'),
('Namsos, Trøndelag','XT'),
('Namsos, Trøndelag','XU'),
('Orkdal, Trøndelag','VX'),
('Orkdal, Trøndelag','VY'),
('Orkdal, Trøndelag','VZ'),
('Steinkjer, Trøndelag','XD'),
('Steinkjer, Trøndelag','XE'),
('Steinkjer, Trøndelag','XF'),
('Steinkjer, Trøndelag','XH'),
('Steinkjer, Trøndelag','XJ'),
('Steinkjer, Trøndelag','XW'),
('Stjørdal, Trøndelag','XN'),
('Støren, Trøndelag','VS'),
('Støren, Trøndelag','VT'),
('Trondheim, Trøndelag','FP'),
('Trondheim, Trøndelag','VD'),
('Trondheim, Trøndelag','VE'),
('Trondheim, Trøndelag','VF'),
('Trondheim, Trøndelag','VH'),
('Trondheim, Trøndelag','VJ'),
('Trondheim, Trøndelag','VK'),
('Trondheim, Trøndelag','VL'),
('Trondheim, Trøndelag','VN'),
('Trondheim, Trøndelag','VP'),
('Trondheim, Trøndelag','VR'),
('Trondheim, Trøndelag','VS'),
('Trondheim, Trøndelag','VU'),
('Trondheim, Trøndelag','VV'),
('Trondheim, Trøndelag','NW'),
('Bodø, Trøndelag','YE'),
('Bodø, Trøndelag','YF'),
('Bodø, Trøndelag','YH'),
('Bodø, Trøndelag','YJ'),
('Bodø, Trøndelag','FD'),
('Bodø, Trøndelag','EZ'),
('Fauske, Nordland','YK'),
('Fauske, Nordland','YL'),
('Mo i Rana, Nordland','YA'),
('Mo i Rana, Nordland','YB'),
('Mo i Rana, Nordland','YC'),
('Mo i Rana, Nordland','YD'),
('Mosjøen, Nordland','XV'),
('Mosjøen, Nordland','XX'),
('Mosjøen, Nordland','XY'),
('Mosjøen, Nordland','XZ'),
('Mosjøen, Nordland','FA'),
('Narvik, Nordland','YN'),
('Narvik, Nordland','YP'),
('Narvik, Nordland','YR'),
('Narvik, Nordland','YS'),
('Sortland, Nordland','YU'),
('Sortland, Nordland','YV'),
('Sortland, Nordland','YX'),
('Svolvær, Nordland','YT'),
('Svolvær, Nordland','YY'),
('Alta, Troms og Finnmark','ZT'),
('Alta, Troms og Finnmark','ZU'),
('Alta, Troms og Finnmark','ZV'),
('Alta, Troms og Finnmark','ZY'),
('Alta, Troms og Finnmark','ZW'),
('Alta, Troms og Finnmark','UW'),
('Finnsnes, Troms og Finnmark','ZD'),
('Finnsnes, Troms og Finnmark','ZF'),
('Finnsnes, Troms og Finnmark','ZJ'),
('Finnsnes, Troms og Finnmark','EX'),
('Hammerfest, Troms og Finnmark','ZX'),
('Hammerfest, Troms og Finnmark','FF'),
('Hammerfest, Troms og Finnmark','EX'),
('Harstad, Troms og Finnmark','YZ'),
('Harstad, Troms og Finnmark','ZA'),
('Harstad, Troms og Finnmark','ZB'),
('Harstad, Troms og Finnmark','TW'),
('Kirkenes, Troms og Finnmark','ZS'),
('Kirkenes, Troms og Finnmark','EY'),
('Lakselv, Troms og Finnmark','ZZ'),
('Lakselv, Troms og Finnmark','CW'),
('Storslett, Troms og Finnmark','FK'),
('Storslett, Troms og Finnmark','SW'),
('Tromsø, Troms og Finnmark','ZC'),
('Tromsø, Troms og Finnmark','ZE'),
('Tromsø, Troms og Finnmark','ZH'),
('Tromsø, Troms og Finnmark','ZK'),
('Tromsø, Troms og Finnmark','ZL'),
('Tromsø, Troms og Finnmark','FC'),
('Vadsø, Troms og Finnmark','FR'),
('Vadsø, Troms og Finnmark','ZP'),
('Vadsø, Troms og Finnmark','ZR'),
('Vadsø, Troms og Finnmark','LE'),
('Svalbard, Troms og Finnmark','ZN'),
('Svalbard, Troms og Finnmark','FH'),
('Electrically powered vehicles','EL'),
('Electrically powered vehicles','EK'),
('Electrically powered vehicles','EV'),
('Electrically powered vehicles','EB'),
('Electrically powered vehicles','EC'),
('Electrically powered vehicles','ED'),
('Electrically powered vehicles','EE'),
('Former military vehicles','FE'),
('autogas/LPG (liquified petroleum gas) or other gas powered vehicles','GA'),
('Hydrogen powered vehicles','HY');
UNLOCK TABLES;

ALTER TABLE norway_entity ADD INDEX norway_index (description, region);