DROP TABLE IF EXISTS `slovakia_entity`;

CREATE TABLE `slovakia_entity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `slovakia_entity` WRITE;
/*!40000 ALTER TABLE `slovakia_entity` DISABLE KEYS */;
INSERT INTO `slovakia_entity` VALUES
(1,'Bratislava','BA'),
(2,'Bratislava','BD'),
(3,'Bratislava','BE'),
(4,'Bratislava','BI'),
(5,'Bratislava','BL'),
(6,'Bratislava','BT'),
(7,'Banská Bystrica','BB'),
(8,'Banská Bystrica','BC'),
(9,'Banská Bystrica','BK'),
(10,'Bardejov','BJ'),
(11,'Bánovce nad Bebravou','BN'),
(12,'Brezno','BR'),
(13,'Banská Štiavnica','BS'),
(15,'Bytča','BY'),
(16,'Čadca','CA'),
(17,'Dolný Kubín','DK'),
(18,'Dunajská Streda','DS'),
(19,'Detva','DT'),
(20,'Galanta','GA'),
(21,'Gelnica','GL'),
(22,'Hlohovec','HC'),
(23,'Humenné','HE'),
(24,'Ilava','IL'),
(25,'Krupina','KA'),
(26,'Košice','KE'),
(27,'Košice','KC'),
(28,'Košice','KI'),
(29,'Kežmarok','KK'),
(30,'Kysucké Nové Mesto','KM'),
(31,'Komárno','KN'),
(32,'Košice-okolie','KS'),
(33,'Lučenec','LC'),
(34,'Levoča','LE'),
(35,'Liptovský Mikuláš','LM'),
(36,'Levice','LV'),
(37,'Levice','LL'),
(38,'Malacky','MA'),
(39,'Michalovce','MI'),
(40,'Medzilaborce','ML'),
(41,'Martin','MT'),
(42,'Myjava','MY'),
(43,'Nitra','NR'),
(44,'Nitra','NI'),
(45,'Nitra','NT'),
(46,'Nové Mesto nad Váhom','NM'),
(47,'Námestovo','NO'),
(48,'Nové Zámky','NZ'),
(49,'Nové Zámky','NC'),
(50,'Považská Bystrica','PB'),
(51,'Prievidza','PD'),
(52,'Partizánske','PE'),
(53,'Pezinok','PK'),
(54,'Piešťany','PN'),
(55,'Prešov','PO'),
(56,'Prešov','PV'),
(57,'Prešov','PS'),
(58,'Poprad','PP'),
(59,'Poltár','PT'),
(60,'Púchov','PU'),
(61,'Revúca','RA'),
(62,'Ružomberok','RK'),
(63,'Rimavská Sobota','RS'),
(64,'Rožňava','RV'),
(65,'Šaľa','SA'),
(66,'Sabinov','SB'),
(67,'Senec','SC'),
(68,'Senica','SE'),
(69,'Skalica','SI'),
(70,'Svidník','SK'),
(71,'Stará Ľubovňa','SL'),
(72,'Spišská Nová Ves','SN'),
(73,'Sobrance','SO'),
(74,'Stropkov','SP'),
(75,'Snina','SV'),
(76,'Trnava','TT'),
(77,'Trnava','TA'),
(78,'Trnava','TB'),
(79,'Trenčín','TN'),
(80,'Trenčín','TC'),
(81,'Trenčín','TE'),
(82,'Topoľčany','TO'),
(83,'Turčianske Teplice','TR'),
(84,'Tvrdošín','TS'),
(85,'Trebišov','TV'),
(86,'Veľký Krtíš','VK'),
(87,'Vranov nad Topľou','VT'),
(88,'Žilina','ZA'),
(89,'Žilina','ZI'),
(90,'Žilina','ZL'),
(91,'Žarnovica','ZC'),
(92,'Žiar nad Hronom','ZH'),
(93,'Zlaté Moravce','ZM'),
(94,'Zvolen','ZV');
UNLOCK TABLES;

ALTER TABLE slovakia_entity ADD INDEX slovakia_index (description, region);
