const countriesForPlates = [
    { value: 'armenia', flag: '🇦🇲', label: 'Armenia' },
    { value: 'austria', flag: '🇦🇹', label: 'Austria' },
    { value: 'azerbaijan', flag: '🇦🇿', label: 'Azerbaijan' },
    { value: 'belarus', flag: '🇧🇾', label: 'Belarus' },
    { value: 'british', flag: '🇻🇬', label: 'Great Britain' },
    { value: 'bulgaria', flag: '🇧🇬', label: 'Bulgaria' },
    { value: 'croatia', flag: '🇭🇷', label: 'Croatia' },
    { value: 'czech', flag: '🇨🇿', label: 'Czech Republic' },
    { value: 'estonia', flag: '🇪🇪', label: 'Estonia' },
    { value: 'france', flag: '🇫🇷', label: 'France' },
    { value: 'germany', flag: '🇩🇪', label: 'Germany' },
    { value: 'greece', flag: '🇬🇷', label: 'Greece' },
    { value: 'hungary', flag: '🇭🇺', label: 'Hungary' },
    { value: 'ireland', flag: '🇮🇪', label: 'Ireland' },
    { value: 'italian', flag: '🇮🇹', label: 'Italy' },
    { value: 'kazakhstan', flag: '🇰🇿', label: 'Kazakhstan' },
    { value: 'kosovo', flag: '🇽🇰', label: 'Kosovo' },
    { value: 'kyrgyzstan', flag: '🇰🇬', label: 'Kyrgyzstan' },
    { value: 'lithuania', flag: '🇱🇹', label: 'Lithuania' },
    { value: 'malaysia', flag: '🇲🇾', label: 'Malaysia' },
    { value: 'moldova', flag: '🇲🇩', label: 'Moldova' },
    { value: 'montenegro', flag: '🇲🇪', label: 'Montenegro' },
    { value: 'norway', flag: '🇳🇴', label: 'Norway' },
    { value: 'macedonia', flag: '🇲🇰', label: 'North Macedonia' },
    { value: 'poland', flag: '🇵🇱', label: 'Poland' },
    { value: 'romania', flag: '🇷🇴', label: 'Romania' },
    { value: 'russia', flag: '🇷🇺', label: 'Russia' },
    { value: 'serbia', flag: '🇷🇸', label: 'Serbia' },
    { value: 'slovakia', flag: '🇸🇰', label: 'Slovakia' },
    { value: 'slovenia', flag: '🇸🇮', label: 'Slovenia' },
    { value: 'sweden', flag: '🇸🇪', label: 'Sweden' },
    { value: 'switzerland', flag: '🇨🇭', label: 'Switzerland' },
    { value: 'turkey', flag: '🇹🇷', label: 'Turkey' },
    { value: 'ukraine', flag: '🇺🇦', label: 'Ukraine' },
    { value: 'uzbekistan', flag: '🇺🇿', label: 'Uzbekistan' },
];

export default countriesForPlates;

