name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
  env:
    MYSQL_DATABASE: regions
    DB_USER: vasko
    DB_PASSWORD: qwerty123456

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔥 Initialize MySQL
        run: sudo systemctl start mysql.service

      - name: 📌 Initialize first database
        run: |
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: 🚀 Boost user
        run: |
          mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';" \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build and run Unit/Integration Tests with Maven
        run: gradle clean build