name: Build Backend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8.2
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      # Setting up the Java environment
      - uses: actions/checkout@v3
      - name: Setup Java 11.*
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          cache: 'gradle'

      # Setting up the Gradle version 7.*
      - name: Setup Gradle 7.*
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Build project.
        run: gradle clean test