name: CI - Build Backend

on:
  pull_request:
    branches:
      - main

jobs:
  springboot:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8.2
        ports:
          - 3306:3306
        env:
          MYSQL_USER: vasko
          MYSQL_PASSWORD: qwerty123456
          MYSQL_DATABASE: regions
          MYSQL_ROOT_PASSWORD: qwerty123456

        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done          
      # Setting up the Java environment
      - uses: actions/checkout@v3
      - name: Setup Java 11.*
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          cache: 'gradle'

      # Setting up the Gradle version 7.*
      - name: Setup Gradle 7.*
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1

      - name: Build project.
        run: gradle clean build test


  cypress-test:
    needs: springboot
    strategy:
      matrix:
        node-version: [ 15.x ]
        os: [ ubuntu-latest ]
        browser: [ chrome, firefox ]

    runs-on: ${{ matrix.os }}

    steps:
      # Setting up the Java environment
      - uses: actions/checkout@v3
      - name: Setup Java 11.*
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          cache: 'gradle'

      # Setting up the Gradle version 7.*
      - name: Setup Gradle 7.*
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1

      - name: Build project.
        run: gradle bootRun &

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --force

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:test -- --browser ${{ matrix.browser }}