name: CI - Build Backend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql:8.0
        env:
          POSTGRES_USER: vasko
          POSTGRES_PASSWORD: qwerty123456
          POSTGRES_DB: regions
        ports:
          - 3306:3306
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build and run Unit/Integration Tests with Maven
        run: gradle clean build