name: Cypress Tests for Split bill application

on:
  workflow_run:
    workflows: ["CI backend"]
    types:
      - completed

jobs:
  Cypress-Test:
    strategy:
      matrix:
        node-version: [ 15.x ]
        os: [ ubuntu-latest ]
        browser: [ chrome, firefox ]

    runs-on: ${{ matrix.os }}

    steps:
      # Setting up the Java environment
      - uses: actions/checkout@v3
      - name: Setup Java 11.*
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          cache: 'gradle'

      # Setting up the Gradle version 7.*
      - name: Setup Gradle 7.*
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1

      - name: Build project.
        run: gradle bootRun &

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --force

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:test -- --browser ${{ matrix.browser }}