name: Build Frontend
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  cypress-test:
    strategy:
      matrix:
        node-version: [ 18.x ]
        os: [ ubuntu-latest ]
        browser: [ chrome, firefox ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci --force

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true
          version: v2.1.0

      - name: Start Docker Containers
        run: |
          docker-compose up --detach --build
          docker-compose exec -T app wait-for-it localhost

      - name: Run Cypress Smoke Tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:smoke:test -- --browser ${{ matrix.browser }}
          parallel: true

      - name: Run Cypress Sanity Tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:sanity:test -- --browser ${{ matrix.browser }}
          parallel: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down