name: Build Frontend
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  cypress-test:
    strategy:
      matrix:
        node-version: [ 18.x ]
        os: [ ubuntu-latest ]
        browser: [ chrome, firefox ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose build --no-cache --force

      - name: Start containers
        run: |
          docker-compose -f "docker-compose.yml" up --detach --build
          for attempt in {1..20}; do sleep 1; if exit 0; then echo ready; break; fi; echo waiting...; done

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci --force

      - name: Run Cypress Smoke Tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:smoke:test -- --browser ${{ matrix.browser }}
          parallel: true

      - name: Run Cypress Sanity Tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:sanity:test -- --browser ${{ matrix.browser }}
          parallel: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down