name: Build Frontend

on:
  workflow_run:
    workflows: [ "Build Backend" ]
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Backend has completed. Triggered Build Frontend."