name: CI-UI tests.

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI - Build Backend" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  cypress-test:
    strategy:
      matrix:
        node-version: [ 15.x ]
        os: [ ubuntu-latest ]
        browser: [ chrome, firefox ]

    services:
      mariadb:
        image: mariadb:10.8.2
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v1
      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      # Setting up the Java environment
      - uses: actions/checkout@v3
      - name: Setup Java 11.*
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          cache: 'gradle'

      # Setting up the Gradle version 7.*
      - name: Setup Gradle 7.*
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1

      - name: Setup Spring Boot App
        run: |
          gradle clean bootRun &
          for attempt in {1..20}; do sleep 1; if exit 0; then echo ready; break; fi; echo waiting...; done

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --force

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run:test -- --browser ${{ matrix.browser }}
